ALTER TABLE wo_evidence DROP CONSTRAINT IF EXISTS ck_wo_evidence_kind;
ALTER TABLE wo_evidence ADD CONSTRAINT ck_wo_evidence_kind CHECK (kind IN (
    'FAT', 'ODP', 'DROPCORE', 'ONT', 'ONU', 'OPTICAL_BEFORE', 'OPTICAL_AFTER',
    'TECHNICIAN_SIGNATURE', 'CUSTOMER_ACKNOWLEDGEMENT', 'BEFORE', 'AFTER', 'LOCATION', 'SERIAL', 'OTHER'
));
