import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { expect, test, type Page } from '@playwright/test'
import { installInfrastructureRoutes } from './platformInfrastructureFixtures'

const evidenceDir = process.env.FTTH_PLATFORM_QA_EVIDENCE_DIR

async function capture(page: Page, name: string) {
  await page.evaluate(async () => { await document.fonts.ready; await new Promise(requestAnimationFrame) })
  const geometry = await page.evaluate(() => {
    const visible = (element: Element) => !element.closest('[hidden], [inert]') && element.getBoundingClientRect().width > 0
    const fields = [...document.querySelectorAll('.horizontal-form .app-field')].filter(visible).map(field => {
      const label = field.querySelector('label'), control = field.querySelector('input,select,[role=combobox]')
      const l = label?.getBoundingClientRect(), c = control?.getBoundingClientRect()
      return { label: label?.textContent, labelLeft: l?.left, labelTop: l?.top, labelBottom: l?.bottom,
        controlLeft: c?.left, controlTop: c?.top, controlRight: c?.right }
    })
    return { width: innerWidth, height: innerHeight, documentWidth: document.documentElement.scrollWidth, fields,
      surfaces: [...document.querySelectorAll('.resource-form-content,.settings-page')].filter(visible).map(element => ({
        width: element.clientWidth, scrollWidth: element.scrollWidth, right: element.getBoundingClientRect().right })) }
  })
  expect(geometry.documentWidth).toBeLessThanOrEqual(geometry.width)
  for (const surface of geometry.surfaces) expect(surface.scrollWidth).toBeLessThanOrEqual(surface.width + 1)
  for (const field of geometry.fields) {
    if (field.controlRight !== undefined) expect(field.controlRight).toBeLessThanOrEqual(geometry.width + 1)
  }
  if (evidenceDir) {
    await mkdir(evidenceDir, { recursive: true })
    await page.screenshot({ path: path.join(evidenceDir, name + '.png'), animations: 'disabled' })
    await writeFile(path.join(evidenceDir, name + '.json'), JSON.stringify(geometry, null, 2))
  }
}

async function discardPanel(page: Page) {
  await page.getByRole('button', { name: 'Tutup', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Buang perubahan?' })).toBeVisible()
  await page.getByRole('button', { name: 'Buang perubahan', exact: true }).click()
  await expect(page.locator('.resource-form-dialog')).toHaveCount(0)
}

for (const width of [375, 768, 1280, 1920]) {
  test('VPN forms retain data and align controls at ' + width, async ({ page }) => {
    const fixture = await installInfrastructureRoutes(page)
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/platform/vpn-servers')
    await expect(page.getByText('Hub QA', { exact: true })).toBeVisible()
    const launcher = page.getByRole('button', { name: 'Tambah hub', exact: true })
    await launcher.click()
    await page.getByRole('textbox', { name: 'Nama hub', exact: false }).fill('Hub Baru')
    await page.getByRole('textbox', { name: 'Host / IP publik VPS', exact: false }).fill('new-vpn.example.test')
    await capture(page, 'vpn-create-' + width)
    expect(fixture.events.filter(event => event.method === 'GET' && event.path === '/api/vpn/servers')).toHaveLength(1)
    await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
    await expect(page.locator('.resource-review-content')).toContainText('Hub Baru')
    await capture(page, 'vpn-review-' + width)
    await page.getByRole('tab', { name: 'Dasar', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Nama hub', exact: false })).toHaveValue('Hub Baru')
    await discardPanel(page)
    await expect(launcher).toBeFocused()
    await page.getByRole('button', { name: 'Aksi baris' }).click()
    await page.getByRole('menuitem', { name: 'Ubah', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Nama hub', exact: false })).toHaveValue('Hub QA')
    await capture(page, 'vpn-edit-' + width)
    await discardPanel(page)
  })

  test('RADIUS uses a retained review flyout at ' + width, async ({ page }) => {
    const fixture = await installInfrastructureRoutes(page)
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/platform/radius-servers')
    await expect(page.getByText('RADIUS QA', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Tambah Node RADIUS', exact: true }).click()
    await page.getByRole('textbox', { name: 'Nama Node Server', exact: true }).fill('Node Baru')
    await page.getByRole('textbox', { name: 'IP Publik / FQDN Host', exact: true }).fill('new-radius.example.test')
    await page.getByRole('textbox', { name: 'Default Shared Secret', exact: true }).fill('synthetic-shared-secret')
    await page.getByRole('textbox', { name: 'JDBC URL', exact: true }).fill('jdbc:postgresql://db.example.test:5432/radius')
    await page.getByRole('textbox', { name: 'Password Database', exact: true }).fill('synthetic-db-secret')
    await page.locator('.resource-form-dialog .fui-DialogContent').evaluate(element => { element.scrollTop = 0 })
    await capture(page, 'radius-create-' + width)
    await page.getByRole('textbox', { name: 'Password Database', exact: true }).scrollIntoViewIfNeeded()
    await capture(page, 'radius-lower-' + width)
    await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
    await expect(page.locator('.resource-review-content')).toContainText('Node Baru')
    await expect(page.locator('.resource-review-content')).not.toContainText('synthetic-db-secret')
    await expect(page.locator('.resource-review-content')).not.toContainText('synthetic-shared-secret')
    await capture(page, 'radius-review-' + width)
    expect(fixture.events.filter(event => event.method === 'GET' && event.path === '/api/platform/radius-servers')).toHaveLength(1)
    await page.getByRole('tab', { name: 'Dasar', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Nama Node Server', exact: true })).toHaveValue('Node Baru')
    await discardPanel(page)
    await expect(page.getByRole('button', { name: 'Tambah Node RADIUS', exact: true })).toBeFocused()
    await page.getByRole('button', { name: 'Aksi baris' }).click()
    await page.getByRole('menuitem', { name: 'Ubah', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Nama Node Server', exact: true })).toHaveValue('RADIUS QA')
    await page.locator('.resource-form-dialog .fui-DialogContent').evaluate(element => { element.scrollTop = 0 })
    await capture(page, 'radius-edit-' + width)
    await page.getByRole('button', { name: 'Uji Koneksi Database', exact: true }).click()
    await expect.poll(() => fixture.events.filter(event => event.path.endsWith('/radius-1/test-connection')).length).toBe(1)
    await page.getByRole('textbox', { name: 'JDBC URL', exact: true }).fill('jdbc:postgresql://other.example.test/radius')
    await page.getByRole('button', { name: 'Uji Koneksi Database', exact: true }).click()
    await expect(page.getByText('Isi password untuk menguji URL atau user database yang berubah', { exact: true })).toBeVisible()
    expect(fixture.events.filter(event => event.path.endsWith('/test-connection'))).toHaveLength(1)
    await discardPanel(page)
  })

  test('Billing fills the available width at ' + width, async ({ page }) => {
    await installInfrastructureRoutes(page)
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/platform/billing')
    await expect(page.getByRole('spinbutton', { name: 'Harga bulanan default (Rp)', exact: true })).toHaveValue('100000')
    await capture(page, 'billing-top-' + width)
    expect(await page.locator('.platform-billing-page').evaluate(element => getComputedStyle(element).maxWidth)).toBe('none')
    const callback = page.getByRole('textbox', { name: 'URL callback Pembayaran', exact: true })
    await callback.scrollIntoViewIfNeeded()
    const action = callback.locator('xpath=ancestor::div[contains(@class, "platform-field-action")]')
    const inputBounds = await callback.boundingBox(), buttonBounds = await action.getByRole('button', { name: 'Salin', exact: true }).boundingBox()
    expect(inputBounds).not.toBeNull()
    expect(buttonBounds).not.toBeNull()
    expect(Math.abs(inputBounds!.y - buttonBounds!.y)).toBeLessThan(3)
    await capture(page, 'billing-callback-' + width)
    await page.getByRole('textbox', { name: 'URL logo', exact: true }).scrollIntoViewIfNeeded()
    await capture(page, 'billing-lower-' + width)
    await page.getByRole('combobox', { name: 'District', exact: true }).fill('bekasi')
    await expect(page.getByRole('listbox').getByRole('option').first()).toBeVisible()
    await capture(page, 'billing-district-' + width)
    await page.keyboard.press('Escape')
  })

  test('ACS settings and console use live platform values at ' + width, async ({ page }) => {
    const fixture = await installInfrastructureRoutes(page)
    await page.setViewportSize({ width, height: 1000 })
    await page.goto('/platform/acs')
    await expect(page.getByRole('textbox', { name: 'NBI URL', exact: false })).toHaveValue(fixture.acs().nbiUrl)
    await expect(page.getByRole('textbox', { name: 'Password API', exact: true })).toHaveValue('')
    await capture(page, 'acs-settings-' + width)
    await page.goto('/acs')
    await expect(page.getByText('http://acs.example.test:7547/', { exact: true }).last()).toBeVisible()
    await capture(page, 'acs-console-' + width)
    const ontCard = page.locator('.card').filter({ has: page.getByRole('heading', { name: 'Setelan ONT (TR-069)', exact: true }) })
    await ontCard.scrollIntoViewIfNeeded()
    await capture(page, 'acs-ont-settings-' + width)
    fixture.setAcs({ nbiUrl: 'https://other-api.example.test', cwmpUrl: 'http://other-acs.example.test:7547/' })
    await page.evaluate(() => window.dispatchEvent(new Event('focus')))
    await expect(page.getByText('http://other-acs.example.test:7547/', { exact: true }).last()).toBeVisible()
    await expect(page.getByText('https://other-api.example.test', { exact: true })).toBeVisible()
  })
}

test('ACS saved testing, discard, failure, busy and retry preserve the draft', async ({ page }) => {
  const fixture = await installInfrastructureRoutes(page)
  await page.setViewportSize({ width: 1280, height: 1000 })
  await page.goto('/platform/acs')
  const nbi = page.getByRole('textbox', { name: 'NBI URL', exact: false })
  const testSaved = page.getByRole('button', { name: 'Uji koneksi tersimpan', exact: true })
  const save = page.getByRole('button', { name: 'Simpan setelan', exact: true })
  await expect(nbi).toHaveValue(fixture.acs().nbiUrl)
  await testSaved.click()
  await expect(page.getByText('API ACS terjangkau', { exact: true })).toBeVisible()
  await capture(page, 'acs-test-success')
  await nbi.fill('https://new-api.example.test')
  await expect(testSaved).toBeDisabled()
  await capture(page, 'acs-dirty')
  await page.getByRole('button', { name: 'Buang perubahan', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Buang perubahan ACS?' })).toBeVisible()
  await capture(page, 'acs-discard')
  await page.getByRole('dialog').getByRole('button', { name: 'Buang perubahan', exact: true }).click()
  await expect(nbi).toHaveValue(fixture.acs().nbiUrl)
  await nbi.fill('https://new-api.example.test')
  fixture.failSave(true)
  await save.click()
  await expect(page.getByText('Gagal menyimpan ACS sintetis', { exact: true })).toBeVisible()
  await expect(nbi).toHaveValue('https://new-api.example.test')
  await capture(page, 'acs-save-error')
  fixture.failSave(false)
  const release = fixture.deferSave()
  await save.evaluate(button => {
    if (!(button instanceof HTMLButtonElement)) throw new Error('Save control must be a button')
    button.click(); button.click()
  })
  await expect(nbi).toBeDisabled()
  await expect(testSaved).toBeDisabled()
  await capture(page, 'acs-saving')
  expect(fixture.events.filter(event => event.method === 'PUT' && event.path === '/api/platform/acs-settings')).toHaveLength(2)
  release()
  await expect(nbi).toBeEnabled()
  await expect(page.getByText('Konfigurasi tersimpan', { exact: true })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Password API', exact: true })).toHaveValue('')
  await capture(page, 'acs-saved')
  await testSaved.click()
  const testEvent = fixture.events.filter(event => event.path === '/api/platform/acs-settings/test').at(-1)
  expect(testEvent?.body).toEqual({})
  fixture.failLoad(true)
  await page.reload()
  await expect(page.getByText('Setelan ACS gagal dimuat.', { exact: true })).toBeVisible()
  await capture(page, 'acs-load-error')
  fixture.failLoad(false)
  await page.getByRole('button', { name: 'Coba lagi', exact: true }).click()
  await expect(nbi).toHaveValue('https://new-api.example.test')
})

test('RADIUS failed writes keep the review and password draft', async ({ page }) => {
  const fixture = await installInfrastructureRoutes(page)
  await page.goto('/platform/radius-servers')
  await page.getByRole('button', { name: 'Aksi baris' }).click()
  await page.getByRole('menuitem', { name: 'Ubah', exact: true }).click()
  await page.getByRole('textbox', { name: 'Nama Node Server', exact: true }).fill('RADIUS Changed')
  await page.getByRole('textbox', { name: /Password Database/ }).fill('synthetic-replacement')
  await page.getByRole('button', { name: 'Tinjau + simpan', exact: true }).click()
  fixture.failRadiusSave(true)
  await page.getByRole('button', { name: 'Simpan node', exact: true }).click()
  await expect(page.getByText('Gagal menyimpan RADIUS sintetis', { exact: true })).toBeVisible()
  await expect(page.locator('.resource-review-content')).toContainText('RADIUS Changed')
  await capture(page, 'radius-save-error')
  await page.getByRole('tab', { name: 'Dasar', exact: true }).click()
  await expect(page.getByRole('textbox', { name: /Password Database/ })).toHaveValue('synthetic-replacement')
  await page.getByRole('textbox', { name: /Password Database/ }).scrollIntoViewIfNeeded()
  await capture(page, 'radius-failed-draft')
})

test('tenant operators cannot enter the platform ACS route', async ({ page }) => {
  const fixture = await installInfrastructureRoutes(page, false)
  await page.goto('/platform/acs')
  await expect(page).toHaveURL('http://127.0.0.1:4188/')
  expect(fixture.events.filter(event => event.path === '/api/platform/acs-settings')).toHaveLength(0)
})

test('VPN and RADIUS review saves send the edited values and retain a blank database password', async ({ page }) => {
  const fixture = await installInfrastructureRoutes(page)
  await page.goto('/platform/vpn-servers')
  await page.getByRole('button', { name: 'Aksi baris' }).click()
  await page.getByRole('menuitem', { name: 'Ubah', exact: true }).click()
  await page.getByRole('textbox', { name: 'Nama hub', exact: false }).fill('Hub Changed')
  await page.getByRole('button', { name: 'Tinjau + simpan', exact: true }).click()
  expect(fixture.events.filter(event => event.method === 'PUT' && event.path === '/api/vpn/servers/vpn-1')).toHaveLength(0)
  await page.getByRole('button', { name: 'Simpan', exact: true }).click()
  await expect(page.locator('.resource-form-dialog')).toHaveCount(0)
  const vpnWrites = fixture.events.filter(event => event.method === 'PUT' && event.path === '/api/vpn/servers/vpn-1')
  expect(vpnWrites).toHaveLength(1)
  expect(vpnWrites[0].body).toMatchObject({ name: 'Hub Changed', host: 'vpn.example.test', port: 1194 })

  await page.goto('/platform/radius-servers')
  await page.getByRole('button', { name: 'Aksi baris' }).click()
  await page.getByRole('menuitem', { name: 'Ubah', exact: true }).click()
  await page.getByRole('textbox', { name: 'Nama Node Server', exact: true }).fill('RADIUS Changed')
  await page.getByRole('button', { name: 'Tinjau + simpan', exact: true }).click()
  expect(fixture.events.filter(event => event.method === 'PUT' && event.path === '/api/platform/radius-servers/radius-1')).toHaveLength(0)
  await page.getByRole('button', { name: 'Simpan node', exact: true }).click()
  await expect(page.locator('.resource-form-dialog')).toHaveCount(0)
  const radiusWrites = fixture.events.filter(event => event.method === 'PUT' && event.path === '/api/platform/radius-servers/radius-1')
  expect(radiusWrites).toHaveLength(1)
  expect(radiusWrites[0].body).toMatchObject({ name: 'RADIUS Changed', dbUser: 'radius', authPort: 1812 })
  expect(radiusWrites[0].body).not.toHaveProperty('dbPassword')
})
