import { expect, test } from '@playwright/test'
import { createUser, login, signup } from './helpers'

test('admin creates B2B client and assigned NE reports private monthly visits', async ({ page }) => {
  test.setTimeout(180_000)
  const owner = await signup(page)
  const engineer = await createUser(page, 'Teknisi NE', { prefix: 'TeknisiNE' })
  const admin = await createUser(page, 'Admin', { prefix: 'AdminB2B' })
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, admin)
  await page.goto('/b2b/clients')
  await page.getByRole('navigation', { name: 'Breadcrumb' }).getByRole('button', { name: 'Lapangan', exact: true }).click()
  await expect(page).toHaveURL(/\/b2b\/clients$/)
  const clientsRoute = '**/api/v1/b2b/clients?*'
  await page.route(clientsRoute, route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ message: 'Layanan client B2B tidak tersedia.' }) }))
  await page.reload()
  await expect(page.getByRole('alert')).toContainText('Layanan client B2B tidak tersedia.')
  await expect(page.getByText('Belum ada client B2B. Tambahkan client untuk menjadwalkan visit.', { exact: true })).toHaveCount(0)
  await page.unroute(clientsRoute)
  await page.getByRole('button', { name: 'Muat ulang', exact: true }).click()
  await expect(page.getByText('Belum ada client B2B. Tambahkan client untuk menjadwalkan visit.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Tambah client B2B', exact: true }).click()
  await page.getByRole('textbox', { name: 'Nama client', exact: true }).fill('Kantor B2B')
  await page.getByRole('textbox', { name: 'Alamat', exact: true }).fill('Jl. Kantor 12')
  await page.getByRole('textbox', { name: 'Kontak / PIC', exact: true }).fill('PIC kantor 08123456789')
  await page.getByRole('spinbutton', { name: 'Target visit per bulan', exact: true }).fill('4')
  await page.getByRole('button', { name: 'Pilih', exact: true }).click()
  await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Tinjau client B2B', exact: true })).toBeVisible()
  const saved = page.waitForResponse(r => new URL(r.url()).pathname === '/api/v1/b2b/clients' && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Simpan', exact: true }).click()
  expect((await saved).status()).toBe(201)
  await expect(page.getByRole('button', { name: 'Kantor B2B', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, engineer)
  await page.goto('/b2b/visits')
  await page.getByRole('navigation', { name: 'Breadcrumb' }).getByRole('button', { name: 'Lapangan', exact: true }).click()
  await expect(page).toHaveURL(/\/b2b\/visits$/)
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', 'base64')
  for (const notes of ['Periksa koneksi kantor', 'Pemeriksaan tambahan']) {
    await page.getByRole('button', { name: 'Laporkan visit', exact: true }).click()
    await page.getByLabel('Catatan visit').fill(notes)
    await page.locator('input[type=file]').setInputFiles({ name: 'proof.png', mimeType: 'image/png', buffer: png })
    await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
    const reported = page.waitForResponse(r => /\/api\/v1\/b2b\/clients\/[^/]+\/visits$/.test(new URL(r.url()).pathname) && r.request().method() === 'POST')
    await page.getByRole('button', { name: 'Kirim laporan visit', exact: true }).click()
    expect((await reported).status()).toBe(201)
    await expect(page.getByRole('dialog')).toHaveCount(0)
  }
  await expect(page.getByRole('gridcell', { name: '1 / 4', exact: true })).toBeVisible()
  await expect(page.getByLabel('Riwayat visit B2B').getByRole('gridcell', { name: 'Tambahan', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, admin)
  await page.goto('/b2b/reports')
  await expect(page.getByRole('gridcell', { name: '1 / 4', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '1 foto · Buka', exact: true }).first().click()
  await expect(page.getByAltText('Bukti visit 1')).toBeVisible()
  await expect.poll(() => page.getByAltText('Bukti visit 1').evaluate(image => image instanceof HTMLImageElement && image.complete && image.naturalWidth > 0)).toBeTruthy()
  await page.getByRole('button', { name: 'Tutup', exact: true }).last().click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, owner)
  await page.goto('/roles')
  for (const name of ['Admin', 'Manager', 'Teknisi NE', 'Teknisi FO']) await expect(page.getByRole('gridcell', { name: `${name} (sistem)`, exact: true })).toBeVisible()
})
