import { expect, test } from '@playwright/test'
import { setupDiscrepancyApprover } from './approvals'
import { prepareCounter, recordBlindCount, startBlindCount, submitBlindCount } from './count-journey'
import { confirmOperation } from './fulfillment'
import { acknowledgeNumericJourney, prepareNumericJourney, switchUser } from './numeric-journey'

test('blind counter, independent rejection and moving transit require an append-only recount without adjusting physical stock', async ({ page }, testInfo) => {
  test.setTimeout(480_000)
  const fixture = await prepareNumericJourney(page, { cableCostMinor: '1000000' })
  const counter = await prepareCounter(page, fixture)
  const checker = await setupDiscrepancyApprover(page, fixture.area.checkboxLabel, [fixture.bin, fixture.transit], [fixture.bin], 'COUNT_VARIANCE')
  const transitCount = await startBlindCount(page, fixture.transit, counter)
  const binCount = await startBlindCount(page, fixture.bin, counter)
  await recordBlindCount(page, counter, transitCount, '100')
  await page.screenshot({ path: testInfo.outputPath('restricted-counter-transit.png'), fullPage: true })
  await recordBlindCount(page, counter, binCount, '899')
  const submitted = await submitBlindCount(page, fixture, binCount)
  expect(submitted).toMatchObject({ state: 'SUBMITTED' })
  await page.getByRole('link', { name: 'Buka persetujuan stock opname', exact: true }).click()
  await page.getByRole('button', { name: 'Periksa persyaratan persetujuan', exact: true }).click()
  await page.getByRole('button', { name: 'Ajukan persetujuan', exact: true }).click()
  const approval = await confirmOperation(page, '/api/v1/warehouse/approvals/request', 'Kirim permintaan persetujuan')
  expect(approval.status).toBe('PENDING')
  await expect(page.getByRole('button', { name: 'Setujui permintaan', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Kembalikan untuk perbaikan', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('count-requester-cannot-decide.png'), fullPage: true })
  await switchUser(page, checker)
  const detailRead = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/approvals/${approval.requestId}/details`)
  await page.goto(`/warehouse/approvals?approvalId=${approval.requestId}`)
  const details = await (await detailRead).json()
  expect(details).toMatchObject({ actions: { canDecide: true }, document: { kind: 'COUNT' } })
  expect(details).not.toHaveProperty('cost')
  await page.getByRole('button', { name: 'Kembalikan untuk perbaikan', exact: true }).click()
  await page.getByRole('textbox', { name: 'Alasan keputusan / referensi pemeriksaan', exact: true }).fill('Bukti selisih belum lengkap; hitung ulang secara independen')
  await page.getByRole('button', { name: 'Tinjau keputusan', exact: true }).click()
  const decision = await confirmOperation(page, '/api/v1/warehouse/approvals/decide', 'Simpan keputusan')
  expect(decision.status).toBe('REWORK_REQUIRED')
  await expect(page.getByRole('region', { name: 'Hasil persetujuan dibukukan', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Ganti ke tema gelap', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  if (testInfo.project.name === 'warehouse-desktop') await page.setViewportSize({ width: 768, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('count-rejection-dark-tablet-or-mobile.png'), fullPage: true })
  if (testInfo.project.name === 'warehouse-desktop') await page.setViewportSize({ width: 1280, height: 900 })
  await page.getByRole('button', { name: 'Ganti ke tema terang', exact: true }).click()
  await acknowledgeNumericJourney(page, fixture)
  await submitBlindCount(page, fixture, transitCount, true)
  await page.screenshot({ path: testInfo.outputPath('transit-count-stale-after-physical-ack.png'), fullPage: true })
  await page.getByRole('button', { name: 'Mulai hitung ulang', exact: true }).click()
  await confirmOperation(page, `/api/v1/warehouse/counts/${transitCount.id}/recount`, 'Konfirmasi stock opname')
  await recordBlindCount(page, counter, transitCount, '0')
  const recounted = await submitBlindCount(page, fixture, transitCount)
  expect(recounted).toMatchObject({ state: 'POSTED' })
  await page.getByText('Riwayat hasil hitung', { exact: true }).click()
  await expect(page.getByText('Bukti: LEMBAR-100', { exact: true })).toBeVisible()
  await expect(page.getByText('Bukti: LEMBAR-0', { exact: true })).toBeVisible()
  const read = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock' && new URL(res.url()).searchParams.get('bucket') === 'AVAILABLE')
  await page.goto('/warehouse/stock?bucket=AVAILABLE')
  const stock = await (await read).json()
  expect(stock.items.find((row: { skuId: string }) => row.skuId === fixture.cable.id)).toMatchObject({ available: { quantityBase: '900000' } })
  expect(stock.items.find((row: { skuId: string }) => row.skuId === fixture.onu.id)).toMatchObject({ available: { quantityBase: '9' } })
  await page.screenshot({ path: testInfo.outputPath('rejected-count-no-stock-adjustment.png'), fullPage: true })
})
