import { expect, test, type Page } from '@playwright/test'
import { writeFileSync } from 'node:fs'
import { prepareNumericJourney, acknowledgeNumericJourney, switchUser } from './numeric-journey'
import { reassignAndCancelWithCustody } from './reassignment-journey'
import { prepareCounter, recordBlindCount, submitBlindCount } from './count-journey'
import { confirmOperation, selectNamed } from './fulfillment'

async function custody(page: Page, workOrderId: string) {
  const response = page.waitForResponse(r => new URL(r.url()).pathname === `/api/v1/warehouse/my-materials/${workOrderId}/custody`)
  await page.goto(`/my-materials?workOrderId=${workOrderId}`)
  const result = await response; expect(result.status()).toBe(200)
  return (await result.json()).items
}
async function stock(page: Page, cableId: string, onuId: string) {
  const response = page.waitForResponse(r => new URL(r.url()).pathname === '/api/v1/warehouse/stock' && new URL(r.url()).searchParams.get('bucket') === 'AVAILABLE')
  await page.goto('/warehouse/stock?bucket=AVAILABLE')
  const result = await response; expect(result.status()).toBe(200)
  const current = await result.json()
  expect(current.items.find((r: { skuId: string }) => r.skuId === cableId)).toMatchObject({ available: { quantityBase: '940000' } })
  expect(current.items.find((r: { skuId: string }) => r.skuId === onuId)).toMatchObject({ available: { quantityBase: '9' } })
  await expect(page.getByRole('row').filter({ hasText: 'Kabel drop' })).toContainText('940,000 m')
  return current
}

test('cancelled reassigned work retains sixty metres while an offline retried forty metre return and blind partial count preserve stock', async ({ page, context }, testInfo) => {
  test.setTimeout(600_000)
  const pageErrors: string[] = []; page.on('pageerror', error => pageErrors.push(error.name))
  const fixture = await prepareNumericJourney(page)
  await acknowledgeNumericJourney(page, fixture)
  await reassignAndCancelWithCustody(page, fixture, testInfo)
  await page.getByRole('button', { name: 'Kembalikan sisa', exact: true }).click()
  await page.getByRole('textbox', { name: 'Jumlah dikembalikan (m)', exact: true }).fill('40')
  await selectNamed(page, 'Karantina tujuan', `${fixture.quarantine.code} · ${fixture.quarantine.name}`)
  await page.getByRole('textbox', { name: 'Referensi bukti pengembalian', exact: true }).fill('F3 pengembalian parsial terukur 40 m')
  await page.getByRole('textbox', { name: 'Alasan pengembalian', exact: true }).fill('Sebagian kabel dibawa kembali setelah pembatalan; 60 m tetap pada petugas asal')
  await page.getByRole('button', { name: 'Tinjau pengembalian', exact: true }).click()
  const path = `${fixture.root}/return`
  const attempts: { key: string | undefined; body: string | null }[] = []
  const observe = (request: import('@playwright/test').Request) => {
    if (new URL(request.url()).pathname === path && request.method() === 'POST') attempts.push({ key: request.headers()['idempotency-key'], body: request.postData() })
  }
  page.on('request', observe)
  await context.setOffline(true)
  await expect(page.getByRole('button', { name: 'Kirim pengembalian', exact: true })).toBeDisabled()
  await expect(page.getByRole('textbox', { name: 'Jumlah dikembalikan (m)', exact: true })).toHaveValue('40')
  expect(attempts).toHaveLength(0)
  await page.screenshot({ path: testInfo.outputPath('offline-partial-return-disabled-retains-command.png'), animations: 'disabled' })
  await context.setOffline(false)
  await expect(page.getByRole('button', { name: 'Kirim pengembalian', exact: true })).toBeEnabled()
  let committed: { status: number; body: string } | undefined
  // Forward the real command, then drop only its reply; no response body is fabricated.
  await page.route(`**${path}`, async route => {
    const response = await route.fetch()
    committed = { status: response.status(), body: await response.text() }
    writeFileSync(testInfo.outputPath('lost-reply.json'), JSON.stringify({ committed, key: route.request().headers()['idempotency-key'], body: route.request().postData() }, null, 2), { mode: 0o600 })
    await route.abort('failed')
  }, { times: 1 })
  await page.getByRole('button', { name: 'Kirim pengembalian', exact: true }).click()
  await expect(page.getByText('Hasil transaksi belum terkonfirmasi. Coba lagi dengan transaksi yang sama sebelum mengubah isinya.', { exact: true })).toBeVisible()
  expect(committed?.status).toBe(200)
  await expect(page.getByRole('button', { name: 'Coba transaksi yang sama', exact: true })).toBeEnabled()
  await expect(page.getByRole('textbox', { name: 'Jumlah dikembalikan (m)', exact: true })).toHaveValue('40')
  await page.screenshot({ path: testInfo.outputPath('lost-reply-partial-return-retains-command.png'), animations: 'disabled' })
  const response = page.waitForResponse(r => new URL(r.url()).pathname === path && r.request().method() === 'POST')
  await page.getByRole('button', { name: 'Coba transaksi yang sama', exact: true }).click()
  const result = await response; expect(result.status()).toBe(200)
  expect(await result.text()).toBe(committed!.body)
  const residual = await result.json()
  page.off('request', observe)
  expect(attempts).toHaveLength(2)
  expect(attempts[0].key).toBeTruthy(); expect(attempts[1]).toEqual(attempts[0])
  const residualRead = page.waitForResponse(r => new URL(r.url()).pathname === `/api/v1/warehouse/my-materials/${fixture.workOrder.id}/residuals` && r.request().method() === 'GET')
  const retained = await custody(page, fixture.workOrder.id)
  const residuals = await (await residualRead).json()
  expect(residuals.items).toHaveLength(1)
  expect(residuals.items[0]).toMatchObject({ id: residual.id, quantityBase: '40000' })
  expect(retained).toHaveLength(2)
  expect(retained.find((row: { baseUnit: string }) => row.baseUnit === 'MM')).toMatchObject({ quantityBase: '60000' })
  expect(retained.find((row: { baseUnit: string }) => row.baseUnit === 'EA')).toMatchObject({ quantityBase: '1' })
  await expect(page.getByRole('button', { name: 'Catat pemakaian', exact: true })).toHaveCount(0)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('cancelled-custody-sixty-metres-retained.png'), fullPage: true, animations: 'disabled' })

  await switchUser(page, fixture.admin)
  await page.goto('/warehouse/returns')
  await page.getByRole('button', { name: 'Lihat sisa menunggu penerimaan', exact: true }).click()
  await page.getByRole('button', { name: 'Akui penerimaan sisa', exact: true }).click()
  await page.getByRole('textbox', { name: 'Bukti penerimaan serah-terima', exact: true }).fill('F3 fisik 40 m diterima')
  await page.getByRole('button', { name: 'Tinjau serah-terima', exact: true }).click()
  await confirmOperation(page, `${fixture.root}/residuals/acknowledge`, 'Akui penerimaan')
  await page.getByRole('button', { name: 'Terima retur baru', exact: true }).click()
  const source = page.getByRole('combobox', { name: 'Sumber retur', exact: true })
  await expect(source.locator(`option[value="${residual.id}"]`)).toBeAttached(); await source.selectOption(residual.id)
  await page.getByRole('textbox', { name: 'Referensi bukti penerimaan retur', exact: true }).fill('F3 kabel 40 m utuh')
  await page.getByRole('button', { name: 'Tinjau penerimaan retur', exact: true }).click()
  const intake = await confirmOperation(page, '/api/v1/warehouse/returns', 'Catat retur')
  await page.getByRole('button', { name: 'Periksa retur', exact: true }).click()
  await page.getByRole('textbox', { name: 'Hasil ukur fisik (m)', exact: true }).fill('40')
  await page.getByRole('combobox', { name: 'Kondisi hasil inspeksi', exact: true }).selectOption('SERVICEABLE')
  await selectNamed(page, 'Rak barang layak pakai', fixture.bin.label)
  await page.getByRole('textbox', { name: 'Referensi bukti tindakan retur', exact: true }).fill('F3 kabel layak masuk rak')
  await page.getByRole('button', { name: 'Tinjau tindakan retur', exact: true }).click()
  const inspected = await confirmOperation(page, `/api/v1/warehouse/returns/${intake.id}/inspect`, 'Catat tindakan retur')
  expect(inspected).toMatchObject({ state: 'ACCEPTED', quantityBase: '40000', stockIdentityId: intake.stockIdentityId })
  const beforeCount = await stock(page, fixture.cable.id, fixture.onu.id)
  const counter = await prepareCounter(page, fixture)
  await page.goto('/warehouse/counts')
  await page.getByRole('button', { name: 'Buat stock opname', exact: true }).click()
  const positionsRead = page.waitForResponse(r => new URL(r.url()).pathname === '/api/v1/warehouse/counts/positions' && new URL(r.url()).searchParams.get('locationId') === fixture.bin.id)
  await selectNamed(page, 'Lokasi stock opname', fixture.bin.label)
  const positions = await (await positionsRead).json()
  const position = positions.items.find((row: { stockIdentityId: string }) => row.stockIdentityId === intake.stockIdentityId)
  expect(position).toBeTruthy()
  await page.getByRole('textbox', { name: 'Alasan stock opname', exact: true }).fill('F3 hanya menghitung potongan 40 m yang diterima; posisi lain tidak ikut disesuaikan')
  const item = page.getByRole('combobox', { name: 'Barang dihitung 1', exact: true })
  await expect(item.locator(`option[value="${position.id}"]`)).toBeAttached(); await item.selectOption(position.id)
  await selectNamed(page, 'Penghitung 1', counter.name)
  await page.getByRole('button', { name: 'Tinjau stock opname', exact: true }).click()
  const count = await confirmOperation(page, '/api/v1/warehouse/counts', 'Simpan stock opname')
  expect(count).toMatchObject({ partialLocation: true, state: 'DRAFT' }); expect(count.entries).toHaveLength(1)
  await page.getByRole('button', { name: 'Mulai penghitungan', exact: true }).click()
  await confirmOperation(page, `/api/v1/warehouse/counts/${count.id}/start`, 'Konfirmasi stock opname')
  await recordBlindCount(page, counter, count, '40')
  await expect(page.getByRole('button', { name: 'Catat hasil Kabel drop · CABLE · REEL-WO', exact: true })).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: 'Kabel drop · CABLE · REEL-WO' })).toContainText('40,000 m')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('blind-counter-returned-piece-only.png'), fullPage: true, animations: 'disabled' })
  const posted = await submitBlindCount(page, fixture, count)
  expect(posted).toMatchObject({ state: 'POSTED' })
  const afterCount = await stock(page, fixture.cable.id, fixture.onu.id)
  await page.getByRole('button', { name: 'Ganti ke tema gelap', exact: true }).click()
  if (testInfo.project.name === 'warehouse-desktop') await page.setViewportSize({ width: 768, height: 900 })
  const sidebar = page.locator('.topbar').getByRole('button', { name: /^(Buka|Tutup) menu$/ })
  if ((await sidebar.getAttribute('aria-expanded')) === 'true') await sidebar.click()
  await expect(sidebar).toHaveAttribute('aria-expanded', 'false')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('partial-return-count-stock-dark.png'), fullPage: true, animations: 'disabled' })
  expect(pageErrors).toEqual([])
  writeFileSync(testInfo.outputPath('edge.json'), JSON.stringify({ workOrderId: fixture.workOrder.id, cableSkuId: fixture.cable.id, onuSkuId: fixture.onu.id, retained, intake, count, beforeCount, afterCount, attempts, committed, residuals }, null, 2), { mode: 0o600 })
})
