import { expect, test } from '@playwright/test'
import { confirmOperation, prepareMaterialWorkOrder, selectNamed } from './fulfillment'

test('warehouse reserves partial demand, picks and unpicks actual pieces, then dispatches to visible transit', async ({ page }, testInfo) => {
  test.setTimeout(240_000)
  const fixture = await prepareMaterialWorkOrder(page)
  const { workOrder, cable, onu, technician, area } = fixture
  const root = `/api/work-orders/${workOrder.id}/materials`
  await page.getByRole('button', { name: 'Susun rencana material', exact: true }).click()
  await selectNamed(page, 'Material 1', `${cable.name} · ${cable.code}`)
  await page.getByRole('textbox', { name: 'Kebutuhan material 1 (m)', exact: true }).fill('100')
  await page.getByRole('checkbox', { name: 'Harus satu potongan utuh', exact: true }).check()
  await page.getByRole('button', { name: 'Tambah material', exact: true }).click()
  await selectNamed(page, 'Material 2', `${onu.name} · ${onu.code}`)
  await page.getByRole('textbox', { name: 'Kebutuhan material 2 (unit)', exact: true }).fill('2')
  await page.getByRole('button', { name: 'Tinjau rencana', exact: true }).click()
  const plan = await confirmOperation(page, `${root}/plan`, 'Simpan rencana', 'PUT')
  expect(plan.lines.map((line: { quantityBase: string }) => line.quantityBase)).toEqual(['100000', '2'])
  await page.getByRole('button', { name: 'Ajukan permintaan', exact: true }).click()
  const submitted = await confirmOperation(page, `${root}/submit-request`, 'Konfirmasi pengajuan')
  expect(submitted).toMatchObject({ demandState: 'SUBMITTED', revisions: { planRevision: 1 } })
  expect(submitted.lines.every((line: { demandLineId: string; planLineId: string }) => line.demandLineId && line.demandLineId !== line.planLineId)).toBeTruthy()
  await page.getByRole('button', { name: 'Reservasi sebagian / pilih stok', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Cadangkan Kabel drop', exact: true }).check()
  await page.getByRole('textbox', { name: 'Reservasi Kabel drop (m)', exact: true }).fill('60')
  await page.getByRole('checkbox', { name: 'Cadangkan ONU pelanggan', exact: true }).check()
  await page.getByRole('textbox', { name: 'Reservasi ONU pelanggan (unit)', exact: true }).fill('1')
  await page.getByRole('button', { name: 'Tinjau reservasi', exact: true }).click()
  const reserved = await confirmOperation(page, `/api/v1/warehouse/material-requests/${submitted.demandDocumentId}/reserve`, 'Cadangkan pilihan')
  expect(reserved).toMatchObject({ state: 'PART_RESERVED', shortage: true })
  await expect(page.getByText(/Masih ada kekurangan material/)).toBeVisible()
  const cableRow = page.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'Kabel drop · CABLE Satu potongan utuh', exact: true }) })
  await expect(cableRow).toContainText('60,000 m')
  await expect(cableRow).toContainText('40,000 m')
  await page.getByRole('button', { name: 'Lepas reservasi', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Pilih REEL-WO', exact: true }).check()
  const releaseAmount = page.getByRole('textbox', { name: 'Jumlah dilepas (m)', exact: true })
  await expect(releaseAmount).toBeDisabled()
  await expect(releaseAmount).toHaveValue('60,000')
  await page.getByRole('textbox', { name: 'Alasan pelepasan reservasi', exact: true }).fill('Tinjau ulang alokasi kabel')
  await page.getByRole('button', { name: 'Tinjau pilihan', exact: true }).click()
  await confirmOperation(page, `/api/v1/warehouse/material-requests/${submitted.demandDocumentId}/release`, 'Lepas pilihan')
  await expect(cableRow.getByRole('gridcell').nth(2).locator('.warehouse-cell-value')).toHaveText('0,000 m')
  await expect(cableRow.getByRole('gridcell').nth(5).locator('.warehouse-cell-value')).toHaveText('100,000 m')
  await expect(page.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'ONU pelanggan · ONU', exact: true }) }).getByRole('gridcell').nth(2).locator('.warehouse-cell-value')).toHaveText('1 unit')
  await page.getByRole('button', { name: 'Reservasi sebagian / pilih stok', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Cadangkan Kabel drop', exact: true }).check()
  await page.getByRole('textbox', { name: 'Reservasi Kabel drop (m)', exact: true }).fill('60')
  await page.getByRole('button', { name: 'Tinjau reservasi', exact: true }).click()
  await confirmOperation(page, `/api/v1/warehouse/material-requests/${submitted.demandDocumentId}/reserve`, 'Cadangkan pilihan')
  await expect(cableRow.getByRole('gridcell').nth(2).locator('.warehouse-cell-value')).toHaveText('60,000 m')
  await expect(cableRow.getByRole('gridcell').nth(5).locator('.warehouse-cell-value')).toHaveText('40,000 m')
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('request-partial.png'), fullPage: true })

  await page.getByText('Persiapan pengeluaran', { exact: true }).click()
  await page.getByRole('button', { name: 'Siapkan transit WO', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Kode lokasi', exact: true })).toHaveValue('WO_TRANSIT')
  await selectNamed(page, 'Area lokasi', area.optionLabel)
  await page.getByRole('button', { name: 'Tinjau perubahan', exact: true }).click()
  await confirmOperation(page, '/api/v1/warehouse/locations', 'Simpan lokasi')
  async function pick() {
    await page.getByRole('button', { name: 'Siapkan barang', exact: true }).click()
    await page.getByRole('checkbox', { name: 'Pilih REEL-WO', exact: true }).check()
    const serialChoice = page.getByRole('checkbox', { name: /^Pilih WO-ONU-/ })
    const serial = (await page.getByRole('group').filter({ has: serialChoice }).locator('legend').innerText()).split(' · ').at(-1)!
    await serialChoice.check()
    const scanner = page.getByRole('textbox', { name: /^Pindai WO-ONU-/ })
    await scanner.fill(serial)
    await scanner.press('Enter')
    await expect(page.getByRole('button', { name: 'Siapkan pilihan', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Tinjau pilihan', exact: true }).click()
    return confirmOperation(page, `${root}/pick`, 'Siapkan pilihan')
  }
  const first = await pick()
  expect(first).toMatchObject({ state: 'PICKED', receiver: { name: technician.name } })
  expect(first.lines.find((line: { baseUnit: string }) => line.baseUnit === 'MM').sourceIdentityId).not.toBe(first.lines.find((line: { baseUnit: string }) => line.baseUnit === 'MM').dimension.stockIdentityId)
  await page.getByRole('button', { name: first.code, exact: true }).click()
  await page.getByRole('textbox', { name: 'Catatan pengiriman / pembatalan', exact: true }).fill('Tinjau ulang persiapan fisik')
  await page.getByRole('button', { name: 'Batal siapkan', exact: true }).click()
  const unpicked = await confirmOperation(page, `${root}/unpick`, 'Konfirmasi batal siapkan')
  expect(unpicked.state).toBe('UNPICKED')
  const second = await pick()
  expect(second.issueId).not.toBe(first.issueId)
  expect(second.lines.find((line: { baseUnit: string }) => line.baseUnit === 'MM').dimension.stockIdentityId).toBe(first.lines.find((line: { baseUnit: string }) => line.baseUnit === 'MM').dimension.stockIdentityId)
  await page.reload()
  await page.getByRole('button', { name: second.code, exact: true }).click()
  const detail = page.getByRole('region', { name: 'Detail slip pengeluaran', exact: true })
  await expect(detail).toContainText(technician.name)
  await expect(detail.getByRole('button', { name: 'Kirim barang', exact: true })).toBeDisabled()
  await detail.getByRole('textbox', { name: 'Catatan pengiriman / pembatalan', exact: true }).fill('Pengiriman pertama: 60m dan satu ONU')
  await detail.getByRole('checkbox', { name: `Konfirmasi penerima: ${technician.name}`, exact: true }).check()
  await expect(detail.getByRole('button', { name: 'Kirim barang', exact: true })).toBeDisabled()
  await detail.getByRole('checkbox', { name: 'Kirim sebagian; sisa kebutuhan masih harus dipenuhi', exact: true }).check()
  await expect(detail.getByRole('button', { name: 'Kirim barang', exact: true })).toBeEnabled()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('issue-review.png'), fullPage: true })
  await detail.getByRole('button', { name: 'Kirim barang', exact: true }).click()
  const dispatched = await confirmOperation(page, `${root}/dispatch`, 'Konfirmasi kirim')
  expect(dispatched).toMatchObject({ state: 'DISPATCHED', receiver: { name: technician.name } })
  expect(dispatched.destinations).toHaveLength(2)
  expect(dispatched.destinations.every((destination: { custodianKind: string }) => destination.custodianKind === 'WAREHOUSE')).toBeTruthy()
  await page.getByRole('button', { name: second.code, exact: true }).click()
  await expect(page.getByRole('region', { name: 'Detail slip pengeluaran', exact: true })).toContainText('Dikirim')
  await expect(page.getByRole('button', { name: 'Kirim barang', exact: true })).toHaveCount(0)
  const slipRead = page.waitForResponse(res => new URL(res.url()).pathname === `${root}/issues/${second.issueId}/slip`)
  await page.getByRole('button', { name: 'Cetak slip', exact: true }).click()
  expect((await slipRead).status()).toBe(200)
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('issue-dispatched.png'), fullPage: true })
  const stockRead = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock' && new URL(res.url()).searchParams.get('bucket') === 'TRANSIT')
  await page.goto('/warehouse/stock?bucket=TRANSIT')
  const stock = await (await stockRead).json()
  expect(stock.items.find((item: { skuId: string }) => item.skuId === cable.id)).toMatchObject({ physical: { quantityBase: '60000' }, available: { quantityBase: '0' } })
  expect(stock.items.find((item: { skuId: string }) => item.skuId === onu.id)).toMatchObject({ physical: { quantityBase: '1' }, available: { quantityBase: '0' } })
  await expect(page.getByRole('row').filter({ hasText: 'Kabel drop' })).toContainText('60,000 m')
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('issue-transit.png'), fullPage: true })
})
