import { expect, test } from '@playwright/test'
import { createRole, createUser, login, openWarehouseMenu, signup } from './helpers'

test('new tenant starts empty and current provenance permission controls real report access', async ({ page, request }, testInfo) => {
  test.setTimeout(180_000)
  await signup(page)
  const reportPromise = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v1/warehouse/provenance')
  await page.goto('/warehouse/provenance')
  const reportResponse = await reportPromise
  expect(reportResponse.ok()).toBeTruthy()
  const report = await reportResponse.json()
  expect(report).toMatchObject({ cutover: { state: 'ENFORCED', epoch: 0 }, batch: null, sourceCount: 0,
    conflictGroupCount: 0, unitUnverifiedBalanceCount: 0, pendingLegacyMovementCount: 0,
    pendingLegacyFulfillmentCount: 0, pendingLegacyOutboxCount: 0 })
  expect(Object.keys(report.sourceCounts)).toHaveLength(10)
  expect(Object.values(report.sourceCounts).every(count => count === 0)).toBeTruthy()
  await expect(page.getByRole('heading', { name: 'Rekonsiliasi Gudang Lama', exact: true })).toBeVisible()
  await expect(page.getByText('Tenant ini sudah aktif tanpa batch rekonsiliasi lama. Gudang dimulai dengan saldo kosong.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /Mulai pemeriksaan|Aktifkan gudang/ })).toHaveCount(0)
  await page.getByText('Lihat jumlah menurut sumber', { exact: true }).click()
  await expect(page.getByRole('region', { name: 'Ringkasan pemeriksaan' }).getByRole('listitem')).toHaveCount(10)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('provenance-empty.png'), fullPage: true })
  await page.getByRole('button', { name: 'Ganti ke tema gelap', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  if (testInfo.project.name === 'warehouse-desktop') await page.setViewportSize({ width: 768, height: 900 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('provenance-empty-dark.png'), fullPage: true })
  if (testInfo.project.name === 'warehouse-desktop') await page.setViewportSize({ width: 1280, height: 900 })
  await page.getByRole('button', { name: 'Ganti ke tema terang', exact: true }).click()
  await page.reload()
  await expect(page.getByText('Tenant ini sudah aktif tanpa batch rekonsiliasi lama. Gudang dimulai dengan saldo kosong.', { exact: true })).toBeVisible()

  await createRole(page, 'Pengelola rekonsiliasi', ['inventory.provenance.manage'])
  const manager = await createUser(page, 'Pengelola rekonsiliasi')
  await createRole(page, 'Pemeriksa persetujuan', ['inventory.approval.view', 'inventory.approval.decide'])
  const approver = await createUser(page, 'Pemeriksa persetujuan')
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, manager)
  await openWarehouseMenu(page)
  await expect(page.getByRole('link', { name: 'Stok & Perangkat', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Rekonsiliasi Data Lama', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Rekonsiliasi Gudang Lama', exact: true })).toBeVisible()
  await expect(page.getByText('Tenant ini sudah aktif tanpa batch rekonsiliasi lama. Gudang dimulai dengan saldo kosong.', { exact: true })).toBeVisible()
  // A new tenant needs no fabricated opening or broad warehouse role to read its empty report.
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, approver)
  await openWarehouseMenu(page)
  await expect(page.getByRole('link', { name: 'Rekonsiliasi Data Lama', exact: true })).toHaveCount(0)
  const approvals = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v1/warehouse/approvals/workbench')
  await page.getByRole('link', { name: 'Persetujuan Gudang', exact: true }).click()
  const authorization = await (await approvals).request().headerValue('authorization')
  expect(authorization).toBeTruthy()
  expect((await request.get('/api/v1/warehouse/provenance', { headers: { Authorization: authorization! } })).status()).toBe(403)
  await page.goto('/warehouse/provenance')
  await expect(page.getByText('Akses gudang dibatasi', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Muat ulang laporan gudang lama', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('provenance-denied.png'), fullPage: true })
})
