import { expect, test, type Page } from '@playwright/test'
import { fileURLToPath } from 'node:url'
import { signup } from './helpers'
import { addLocation, addSku, addSupplier, setupOwnArea } from './catalog'

async function select(page: Page, name: string, label: string) {
  const control = page.getByRole('combobox', { name, exact: true })
  await expect(control).toBeEnabled()
  await expect(control.getByRole('option', { name: label, exact: true })).toBeAttached()
  await control.selectOption({ label })
}
async function transition(page: Page, id: string, action: string, button: string) {
  const response = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/receipts/${id}/${action}` && res.request().method() === 'POST')
  await page.getByRole('button', { name: button, exact: true }).click()
  const result = await response
  expect(result.status()).toBe(200)
  return result.json()
}

test('real receipt receives 1000 metres and10 ONUs, rejects a subset and puts away accepted goods in stages', async ({ page }, testInfo) => {
  test.setTimeout(240_000)
  const admin = await signup(page)
  const area = await setupOwnArea(page, admin)
  const warehouse = await addLocation(page, { code: 'MAIN', name: 'Gudang utama', area: area.optionLabel })
  const bin = await addLocation(page, { code: 'BIN-A', name: 'Rak A', area: area.optionLabel, kind: 'BIN', parent: warehouse.label })
  const quarantine = await addLocation(page, { code: 'QA', name: 'Pemeriksaan barang', area: area.optionLabel, kind: 'QUARANTINE' })
  const cable = await addSku(page, { code: 'CABLE', name: 'Kabel drop', tracking: 'LOT', unit: 'MM' })
  const onu = await addSku(page, { code: 'ONU', name: 'ONU pelanggan', tracking: 'SERIAL' })
  const supplier = await addSupplier(page, 'DISTRIB', 'Distributor material')
  await page.goto('/warehouse/receipts')
  await page.getByText('Persiapan penerimaan', { exact: true }).click()
  await page.getByRole('button', { name: 'Siapkan batas penerimaan', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Kode lokasi', exact: true })).toHaveValue('RECEIPT_SOURCE')
  await expect(page.getByRole('combobox', { name: 'Jenis lokasi', exact: true })).toHaveValue('TRANSIT')
  await select(page, 'Area lokasi', area.optionLabel)
  await page.getByRole('button', { name: 'Tinjau perubahan', exact: true }).click()
  const sourceSaved = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/locations' && res.request().method() === 'POST')
  await page.getByRole('button', { name: 'Simpan lokasi', exact: true }).click()
  expect((await sourceSaved).status()).toBe(201)
  await page.getByRole('button', { name: 'Buat penerimaan', exact: true }).click()
  await page.getByRole('textbox', { name: 'Referensi surat jalan', exact: true }).fill('SJ-1000-10')
  await select(page, 'Pemasok', `${supplier.name} · ${supplier.code}`)
  await select(page, 'Batas penerimaan', 'Penerimaan pemasok · RECEIPT_SOURCE')
  await select(page, 'Lokasi pemeriksaan', quarantine.label)
  await select(page, 'Barang 1', `${cable.name} · ${cable.code}`)
  await page.getByRole('textbox', { name: 'Panjang reel aktual (m)', exact: true }).fill('1000,000')
  await page.getByRole('textbox', { name: 'Kode lot / reel', exact: true }).fill('REEL-001')
  await page.getByText('Konversi kemasan dan biaya', { exact: true }).click()
  await page.getByRole('checkbox', { name: 'Catat biaya kelompok barang', exact: true }).check()
  await page.getByRole('textbox', { name: 'Total biaya (satuan minor)', exact: true }).fill('1000006')
  await page.getByRole('button', { name: 'Tambah baris barang', exact: true }).click()
  await select(page, 'Barang 2', `${onu.name} · ${onu.code}`)
  await page.getByRole('textbox', { name: 'Jumlah aktual (unit)', exact: true }).fill('10')
  const serials = Array.from({ length: 10 }, (_, i) => `ONU-${String(i + 1).padStart(3, '0')}`)
  await page.getByRole('textbox', { name: 'Serial dan MAC', exact: true }).fill([...serials.slice(0, 9), serials[0]].join('\n'))
  await page.getByRole('button', { name: 'Tinjau draft', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Serial ganda')
  await page.getByRole('textbox', { name: 'Serial dan MAC', exact: true }).fill(serials.slice(0, 9).join('\n'))
  await page.getByRole('textbox', { name: 'Pindai serial baru', exact: true }).fill(serials[9])
  await page.getByRole('textbox', { name: 'Pindai serial baru', exact: true }).press('Enter')
  await expect(page.getByRole('textbox', { name: 'Serial dan MAC', exact: true })).toHaveValue(serials.join('\n'))
  await expect(page.getByRole('button', { name: 'Simpan draft', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Tinjau draft', exact: true }).click()
  const created = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/receipts' && res.request().method() === 'POST')
  await page.getByRole('button', { name: 'Simpan draft', exact: true }).click()
  const createResponse = await created
  expect(createResponse.status()).toBe(201)
  const draft = await createResponse.json()
  expect(draft).toMatchObject({ revision: 0, state: 'DRAFT', costVisible: false })
  expect(draft.lines).toHaveLength(11)
  expect(draft.lines.every((line: { pieces: unknown[] }) => line.pieces.length === 0)).toBeTruthy()
  const id = draft.id as string
  await expect(page.getByRole('button', { name: 'Ubah draft', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Ubah draft', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Jumlah aktual (unit)', exact: true })).toHaveValue('10')
  await page.getByRole('textbox', { name: 'Referensi surat jalan', exact: true }).fill('SJ-1000-10-VALID')
  await page.getByRole('button', { name: 'Tinjau draft', exact: true }).click()
  const updated = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/receipts/${id}` && res.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Simpan draft', exact: true }).click()
  const updateResponse = await updated
  expect(updateResponse.status()).toBe(200)
  const updateInput = updateResponse.request().postDataJSON()
  expect(updateInput.lines).toHaveLength(2)
  expect(updateInput.lines[0].cost).toEqual({ totalMinor: '1000006', currency: 'IDR' })
  await expect(page.getByRole('heading', { name: 'SJ-1000-10-VALID', exact: true })).toBeVisible()
  await page.getByLabel('File bukti (PNG, JPEG, PDF; maksimal 15 MiB)', { exact: true }).setInputFiles(fileURLToPath(new URL('./fixtures/inspection.png', import.meta.url)))
  await page.getByRole('button', { name: 'Tinjau unggahan', exact: true }).click()
  const uploaded = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/receipts/${id}/attachments` && res.request().method() === 'POST')
  await page.getByRole('button', { name: 'Unggah bukti', exact: true }).click()
  const uploadResponse = await uploaded
  expect(uploadResponse.status()).toBe(201)
  const evidence = await uploadResponse.json()
  await expect(page.getByText('Sesuai draft saat ini', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Sesuai draft saat ini', { exact: true })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Unduh bukti', exact: true }).click()
  expect((await download).suggestedFilename()).toBe(`bukti-${evidence.id}.png`)
  await page.getByRole('button', { name: 'Terima barang', exact: true }).click()
  const received = await transition(page, id, 'receive', 'Konfirmasi penerimaan')
  expect(received).toMatchObject({ revision: 3, state: 'RECEIVED_IN_INSPECTION' })
  expect(received.lines.every((line: { pieces: { status: string }[] }) => line.pieces.length === 1 && line.pieces[0].status === 'QUARANTINE')).toBeTruthy()
  await page.getByRole('button', { name: 'Periksa barang', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Bukti pemeriksaan', exact: true })).toBeEnabled()
  await page.getByRole('combobox', { name: 'Bukti pemeriksaan', exact: true }).selectOption(evidence.id)
  await page.getByRole('textbox', { name: 'Alasan / hasil pemeriksaan', exact: true }).fill('Uji penerimaan: kabel rusak 100m dan dua ONU tidak lolos.')
  await page.getByRole('button', { name: 'Terima semua sisa yang ditampilkan', exact: true }).click()
  await page.getByRole('textbox', { name: 'Diterima (m)', exact: true }).fill('900,000')
  await page.getByRole('textbox', { name: 'Ditolak (m)', exact: true }).fill('100,000')
  for (const serial of serials.slice(8)) await page.getByRole('combobox', { name: `Keputusan ${serial}`, exact: true }).selectOption('reject')
  await page.getByRole('button', { name: 'Tinjau pemeriksaan', exact: true }).click()
  const inspected = await transition(page, id, 'inspect', 'Simpan pemeriksaan')
  expect(inspected).toMatchObject({ revision: 4, state: 'RECEIVED_IN_INSPECTION' })
  expect(inspected.lines.find((line: { skuId: string }) => line.skuId === cable.id)).toMatchObject({ acceptedBase: '900000', rejectedBase: '100000', putawayBase: '0' })
  expect(inspected.inspections).toHaveLength(11)
  await page.getByRole('button', { name: 'Tempatkan ke bin', exact: true }).click()
  await select(page, 'Bin tujuan', bin.label)
  await expect(page.getByRole('checkbox', { name: 'Tempatkan ONU-009', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Pilih semua yang memenuhi syarat', exact: true }).click()
  await page.getByRole('textbox', { name: 'Jumlah penempatan (m)', exact: true }).fill('800,000')
  await page.getByRole('button', { name: 'Tinjau penempatan', exact: true }).click()
  const partial = await transition(page, id, 'putaway', 'Tempatkan barang')
  expect(partial).toMatchObject({ revision: 5, state: 'RECEIVED_IN_INSPECTION' })
  await page.getByRole('button', { name: 'Tempatkan ke bin', exact: true }).click()
  await select(page, 'Bin tujuan', bin.label)
  await page.getByRole('button', { name: 'Pilih semua yang memenuhi syarat', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Jumlah penempatan (m)', exact: true })).toHaveValue('100,000')
  await page.getByRole('button', { name: 'Tinjau penempatan', exact: true }).click()
  const final = await transition(page, id, 'putaway', 'Tempatkan barang')
  expect(final).toMatchObject({ revision: 6, state: 'PUTAWAY' })
  expect(final.lines.find((line: { skuId: string }) => line.skuId === cable.id)).toMatchObject({ quantityBase: '1000000', acceptedBase: '900000', rejectedBase: '100000', putawayBase: '900000' })
  expect(final.lines.filter((line: { skuId: string; putawayBase: string }) => line.skuId === onu.id && line.putawayBase === '1')).toHaveLength(8)
  await expect(page.getByText('Selesai ditempatkan', { exact: true })).toBeVisible()
  await page.getByText('Riwayat penerimaan', { exact: true }).click()
  await expect(page.getByRole('list', { name: 'Riwayat dokumen' }).getByRole('listitem')).toHaveCount(7)
  const reference = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Simpan referensi', exact: true }).click()
  expect((await reference).suggestedFilename()).toBe(`penerimaan-${id}-r6.txt`)
  await page.getByRole('heading', { name: 'Penerimaan Barang', exact: true }).scrollIntoViewIfNeeded()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('receipt-complete.png') })
  await page.goto('/warehouse/stock')
  const cableRow = page.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'Kabel drop CABLE', exact: true }) })
  await expect(cableRow.getByRole('gridcell', { name: '900,000 m', exact: true })).toHaveCount(1)
  const onuRow = page.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'ONU pelanggan ONU', exact: true }) })
  await expect(onuRow.getByRole('gridcell', { name: '8 unit', exact: true })).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('received-stock.png'), fullPage: true })
})
