import { expect, test, type Page } from '@playwright/test'
import { fileURLToPath } from 'node:url'
import { signup } from './helpers'
import { addLocation, addSku, addSupplier, setupOwnArea } from './catalog'

async function select(page: Page, name: string, label: string) {
  const control = page.getByRole('combobox', { name, exact: true })
  await expect(control).toBeEnabled()
  await expect(control.getByRole('option', { name: label, exact: true })).toBeAttached()
  await control.selectOption({ label })
}
async function transition(page: Page, id: string, action: string, button: string) {
  const response = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/receipts/${id}/${action}` && res.request().method() === 'POST')
  const refreshed = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/receipts/${id}` && res.request().method() === 'GET')
  await page.getByRole('button', { name: button, exact: true }).click()
  const result = await response
  expect(result.status()).toBe(200)
  const confirmed = await result.json()
  expect(confirmed.operationId).toBeTruthy()
  const detail = await refreshed
  expect(detail.ok()).toBeTruthy()
  const snapshot = await detail.json()
  expect(snapshot).toMatchObject({ id, revision: confirmed.revision, state: confirmed.state })
  return snapshot
}

test('real receipt receives and inspects 1000 metres and10 ONUs, then traces scoped stock, serials and reel pieces', async ({ page }, testInfo) => {
  test.setTimeout(240_000)
  const admin = await signup(page)
  const area = await setupOwnArea(page, admin)
  const warehouse = await addLocation(page, { code: 'MAIN', name: 'Gudang utama', area: area.optionLabel })
  const bin = await addLocation(page, { code: 'BIN-A', name: 'Rak A', area: area.optionLabel, kind: 'BIN', parent: warehouse.label })
  const quarantine = await addLocation(page, { code: 'QA', name: 'Pemeriksaan barang', area: area.optionLabel, kind: 'QUARANTINE' })
  const cable = await addSku(page, { code: 'CABLE', name: 'Kabel drop', tracking: 'LOT', unit: 'MM', minimum: '1000' })
  const onu = await addSku(page, { code: 'ONU', name: 'ONU pelanggan', tracking: 'SERIAL' })
  const supplier = await addSupplier(page, 'DISTRIB', 'Distributor material')
  await page.goto('/warehouse/receipts')
  await page.getByText('Persiapan penerimaan', { exact: true }).click()
  await page.getByRole('button', { name: 'Siapkan batas penerimaan', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Kode lokasi', exact: true })).toHaveValue('RECEIPT_SOURCE')
  await expect(page.getByRole('combobox', { name: 'Jenis lokasi', exact: true })).toHaveValue('TRANSIT')
  await select(page, 'Area lokasi', area.optionLabel)
  await page.getByRole('button', { name: 'Tinjau perubahan', exact: true }).click()
  const sourceSaved = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/locations' && res.request().method() === 'POST')
  await page.getByRole('button', { name: 'Simpan lokasi', exact: true }).click()
  expect((await sourceSaved).status()).toBe(201)
  await page.getByRole('button', { name: 'Buat penerimaan', exact: true }).click()
  await page.getByRole('textbox', { name: 'Referensi surat jalan', exact: true }).fill('SJ-1000-10')
  await select(page, 'Pemasok', `${supplier.name} · ${supplier.code}`)
  await select(page, 'Batas penerimaan', 'Penerimaan pemasok · RECEIPT_SOURCE')
  await select(page, 'Lokasi pemeriksaan', quarantine.label)
  await select(page, 'Barang 1', `${cable.name} · ${cable.code}`)
  await page.getByRole('textbox', { name: 'Panjang reel aktual (m)', exact: true }).fill('1000,000')
  await page.getByRole('textbox', { name: 'Kode lot / reel', exact: true }).fill('REEL-001')
  await page.getByText('Konversi kemasan dan biaya', { exact: true }).click()
  await page.getByRole('checkbox', { name: 'Catat biaya kelompok barang', exact: true }).check()
  await page.getByRole('textbox', { name: 'Total biaya (satuan minor)', exact: true }).fill('1000006')
  await page.getByRole('button', { name: 'Tambah baris barang', exact: true }).click()
  await select(page, 'Barang 2', `${onu.name} · ${onu.code}`)
  await page.getByRole('textbox', { name: 'Jumlah aktual (unit)', exact: true }).fill('10')
  const serials = Array.from({ length: 10 }, (_, i) => `ONU-${String(i + 1).padStart(3, '0')}`)
  await page.getByRole('textbox', { name: 'Serial dan MAC', exact: true }).fill([...serials.slice(0, 9), serials[0]].join('\n'))
  await page.getByRole('button', { name: 'Tinjau draft', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Serial ganda')
  await page.getByRole('textbox', { name: 'Serial dan MAC', exact: true }).fill(serials.slice(0, 9).join('\n'))
  await page.getByRole('textbox', { name: 'Pindai serial baru', exact: true }).fill(serials[9])
  await page.getByRole('textbox', { name: 'Pindai serial baru', exact: true }).press('Enter')
  await expect(page.getByRole('textbox', { name: 'Serial dan MAC', exact: true })).toHaveValue(serials.join('\n'))
  await expect(page.getByRole('button', { name: 'Simpan draft', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Tinjau draft', exact: true }).click()
  const created = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/receipts' && res.request().method() === 'POST')
  await page.getByRole('button', { name: 'Simpan draft', exact: true }).click()
  const createResponse = await created
  expect(createResponse.status()).toBe(201)
  const draft = await createResponse.json()
  expect(draft).toMatchObject({ revision: 0, state: 'DRAFT', costVisible: false })
  expect(draft.lines).toHaveLength(11)
  expect(draft.lines.every((line: { pieces: unknown[] }) => line.pieces.length === 0)).toBeTruthy()
  const id = draft.id as string
  await expect(page.getByRole('button', { name: 'Ubah draft', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Ubah draft', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Jumlah aktual (unit)', exact: true })).toHaveValue('10')
  await page.getByRole('textbox', { name: 'Referensi surat jalan', exact: true }).fill('SJ-1000-10-VALID')
  await page.getByRole('button', { name: 'Tinjau draft', exact: true }).click()
  const updated = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/receipts/${id}` && res.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Simpan draft', exact: true }).click()
  const updateResponse = await updated
  expect(updateResponse.status()).toBe(200)
  const updateInput = updateResponse.request().postDataJSON()
  expect(updateInput.lines).toHaveLength(2)
  expect(updateInput.lines[0].cost).toEqual({ totalMinor: '1000006', currency: 'IDR' })
  await expect(page.getByRole('heading', { name: 'SJ-1000-10-VALID', exact: true })).toBeVisible()
  await page.getByLabel('File bukti (PNG, JPEG, PDF; maksimal 15 MiB)', { exact: true }).setInputFiles(fileURLToPath(new URL('./fixtures/inspection.png', import.meta.url)))
  await page.getByRole('button', { name: 'Tinjau unggahan', exact: true }).click()
  const uploaded = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/receipts/${id}/attachments` && res.request().method() === 'POST')
  await page.getByRole('button', { name: 'Unggah bukti', exact: true }).click()
  const uploadResponse = await uploaded
  expect(uploadResponse.status()).toBe(201)
  const evidence = await uploadResponse.json()
  await expect(page.getByText('Sesuai draft saat ini', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('Sesuai draft saat ini', { exact: true })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Unduh bukti', exact: true }).click()
  expect((await download).suggestedFilename()).toBe(`bukti-${evidence.id}.png`)
  await page.getByRole('button', { name: 'Terima barang', exact: true }).click()
  const received = await transition(page, id, 'receive', 'Konfirmasi penerimaan')
  expect(received).toMatchObject({ revision: 3, state: 'RECEIVED_IN_INSPECTION' })
  expect(received.lines.every((line: { pieces: { status: string }[] }) => line.pieces.length === 1 && line.pieces[0].status === 'QUARANTINE')).toBeTruthy()
  await page.getByRole('button', { name: 'Periksa barang', exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Bukti pemeriksaan', exact: true })).toBeEnabled()
  await page.getByRole('combobox', { name: 'Bukti pemeriksaan', exact: true }).selectOption(evidence.id)
  await page.getByRole('textbox', { name: 'Alasan / hasil pemeriksaan', exact: true }).fill('Uji penerimaan: kabel rusak 100m dan dua ONU tidak lolos.')
  await page.getByRole('button', { name: 'Terima semua sisa yang ditampilkan', exact: true }).click()
  await page.getByRole('textbox', { name: 'Diterima (m)', exact: true }).fill('900,000')
  await page.getByRole('textbox', { name: 'Ditolak (m)', exact: true }).fill('100,000')
  for (const serial of serials.slice(8)) await page.getByRole('combobox', { name: `Keputusan ${serial}`, exact: true }).selectOption('reject')
  await page.getByRole('button', { name: 'Tinjau pemeriksaan', exact: true }).click()
  const inspected = await transition(page, id, 'inspect', 'Simpan pemeriksaan')
  expect(inspected).toMatchObject({ revision: 4, state: 'RECEIVED_IN_INSPECTION' })
  expect(inspected.lines.find((line: { skuId: string }) => line.skuId === cable.id)).toMatchObject({ acceptedBase: '900000', rejectedBase: '100000', putawayBase: '0' })
  expect(inspected.inspections).toHaveLength(11)
  await page.getByRole('button', { name: 'Tempatkan ke bin', exact: true }).click()
  await select(page, 'Bin tujuan', bin.label)
  await expect(page.getByRole('checkbox', { name: 'Tempatkan ONU-009', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Pilih semua yang memenuhi syarat', exact: true }).click()
  await page.getByRole('textbox', { name: 'Jumlah penempatan (m)', exact: true }).fill('800,000')
  await page.getByRole('button', { name: 'Tinjau penempatan', exact: true }).click()
  const partial = await transition(page, id, 'putaway', 'Tempatkan barang')
  expect(partial).toMatchObject({ revision: 5, state: 'RECEIVED_IN_INSPECTION' })
  await page.getByRole('button', { name: 'Tempatkan ke bin', exact: true }).click()
  await select(page, 'Bin tujuan', bin.label)
  await page.getByRole('button', { name: 'Pilih semua yang memenuhi syarat', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Jumlah penempatan (m)', exact: true })).toHaveValue('100,000')
  await page.getByRole('button', { name: 'Tinjau penempatan', exact: true }).click()
  const final = await transition(page, id, 'putaway', 'Tempatkan barang')
  expect(final).toMatchObject({ revision: 6, state: 'PUTAWAY' })
  expect(final.lines.find((line: { skuId: string }) => line.skuId === cable.id)).toMatchObject({ quantityBase: '1000000', acceptedBase: '900000', rejectedBase: '100000', putawayBase: '900000' })
  expect(final.lines.filter((line: { skuId: string; putawayBase: string }) => line.skuId === onu.id && line.putawayBase === '1')).toHaveLength(8)
  await expect(page.getByText('Selesai ditempatkan', { exact: true })).toBeVisible()
  await page.getByText('Riwayat penerimaan', { exact: true }).click()
  await expect(page.getByRole('list', { name: 'Riwayat dokumen' }).getByRole('listitem')).toHaveCount(7)
  const reference = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Simpan referensi', exact: true }).click()
  expect((await reference).suggestedFilename()).toBe(`penerimaan-${id}-r6.txt`)
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('receipt-complete.png') })
  await page.goto('/warehouse/stock')
  const cableRow = page.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'Kabel drop CABLE', exact: true }) })
  await expect(cableRow.getByRole('gridcell', { name: '900,000 m', exact: true })).toHaveCount(1)
  const onuRow = page.getByRole('row').filter({ has: page.getByRole('gridcell', { name: 'ONU pelanggan ONU', exact: true }) })
  await expect(onuRow.getByRole('gridcell', { name: '8 unit', exact: true })).toHaveCount(1)
  await expect(cableRow.getByText('Di bawah minimum', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('received-stock.png'), fullPage: true })

  const explorerMutations: string[] = []
  page.on('request', request => { if (new URL(request.url()).pathname.startsWith('/api/v1/warehouse/') && !['GET', 'HEAD'].includes(request.method())) explorerMutations.push(request.method() + ' ' + new URL(request.url()).pathname) })
  await page.getByRole('tab', { name: 'Perangkat serial', exact: true }).click()
  await page.getByText('Cari atau pindai perangkat', { exact: true }).click()
  await page.getByRole('textbox', { name: 'Serial atau MAC', exact: true }).fill('ONU-001')
  await page.getByRole('textbox', { name: 'Serial atau MAC', exact: true }).press('Enter')
  const assetResponse = page.waitForResponse(res => /\/warehouse\/assets\/[^/]+$/.test(new URL(res.url()).pathname) && !res.url().includes('/lookup') && res.request().method() === 'GET')
  const traceResponse = page.waitForResponse(res => /\/warehouse\/assets\/[^/]+\/history$/.test(new URL(res.url()).pathname))
  await page.getByRole('link', { name: 'Buka perangkat ONU-001', exact: true }).click()
  const asset = await (await assetResponse).json()
  expect(asset).toMatchObject({ serial: 'ONU-001', locationName: 'Rak A', status: 'AVAILABLE', legalOwner: 'ISP', admission: 'VERIFIED', origin: { documentId: id }, cost: { state: 'UNKNOWN' } })
  const trace = await (await traceResponse).json()
  expect(trace.totalElements).toBe(5)
  expect(trace.items.filter((event: { kind: string }) => event.kind === 'MOVEMENT_LEG')).toHaveLength(4)
  expect(trace.items.filter((event: { kind: string }) => event.kind === 'INSPECTION')).toHaveLength(1)
  const assetDetail = page.getByRole('region', { name: 'Detail perangkat', exact: true })
  await expect(assetDetail).toContainText('Rak A')
  await expect(assetDetail.getByText('Biaya asal belum diketahui.', { exact: true })).toBeVisible()
  await expect(assetDetail.getByRole('link', { name: asset.origin.documentCode, exact: true })).toHaveAttribute('href', `/warehouse/receipts?id=${id}`)
  await expect(page.getByRole('region', { name: 'Jejak barang', exact: true }).getByRole('row')).toHaveCount(6)
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('stock-serial-trace.png'), fullPage: true })

  await page.getByRole('link', { name: 'Kembali ke perangkat', exact: true }).click()
  await page.getByRole('tab', { name: 'Lot / reel', exact: true }).click()
  const lotResponse = page.waitForResponse(res => /\/warehouse\/lots\/[^/]+$/.test(new URL(res.url()).pathname))
  const segmentsResponse = page.waitForResponse(res => /\/warehouse\/lots\/[^/]+\/segments$/.test(new URL(res.url()).pathname))
  await page.getByRole('link', { name: 'REEL-001', exact: true }).click()
  const lot = await (await lotResponse).json(), segments = await (await segmentsResponse).json()
  expect(lot).toMatchObject({ received: { quantityBase: '1000000', baseUnit: 'MM' }, origin: { documentId: id }, cost: { state: 'KNOWN', totalMinor: '1000006', costBasisQuantityBase: '1000000', currency: 'IDR' },
    conservation: { consistent: true, activeQuantityBase: '1000000', rootQuantityBase: '1000000', rootCount: 1, splitCount: 2 } })
  expect(segments.totalElements).toBe(5)
  expect(segments.items.filter((part: { state: string }) => part.state === 'ACTIVE')).toHaveLength(3)
  const root = segments.items.find((part: { parentSegmentId: string | null }) => part.parentSegmentId === null)
  expect(root).toMatchObject({ state: 'SPLIT', childCount: 2, conserved: true })
  await expect(page.getByText('Jumlah reel dan seluruh bagiannya konsisten.', { exact: true })).toBeVisible()
  const parts = page.getByRole('region', { name: 'Bagian reel', exact: true })
  await expect(parts.getByRole('row')).toHaveCount(6)
  await expect(parts.getByRole('gridcell', { name: 'Sudah dipecah', exact: true })).toHaveCount(2)
  await parts.getByRole('link', { name: `Reel asal · ${root.id.slice(0, 8)}`, exact: true }).click()
  const partDetail = page.getByRole('region', { name: 'Detail bagian reel', exact: true })
  await expect(partDetail.getByRole('link', { name: /^Buka bagian / })).toHaveCount(2)
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('stock-reel-lineage.png'), fullPage: true })
  await page.getByRole('region', { name: 'Detail lot', exact: true }).getByRole('link', { name: lot.origin.documentCode, exact: true }).click()
  await expect(page.getByText('Selesai ditempatkan', { exact: true })).toBeVisible()

  await page.goto('/warehouse/stock')
  await page.getByText('Filter stok', { exact: true }).click()
  await select(page, 'Lokasi stok', quarantine.label)
  await page.getByRole('combobox', { name: 'Kelompok stok', exact: true }).selectOption('QUARANTINE')
  const filteredResponse = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock' && new URL(res.url()).searchParams.get('bucket') === 'QUARANTINE')
  await page.getByRole('button', { name: 'Terapkan filter', exact: true }).click()
  const filtered = await (await filteredResponse).json()
  expect(filtered.totalElements).toBe(2)
  expect(filtered.items.find((row: { skuId: string }) => row.skuId === cable.id)).toMatchObject({ physical: { quantityBase: '100000' }, available: { quantityBase: '0' } })
  expect(filtered.items.find((row: { skuId: string }) => row.skuId === onu.id)).toMatchObject({ physical: { quantityBase: '2' }, available: { quantityBase: '0' } })
  await page.getByRole('link', { name: 'Kabel drop', exact: true }).click()
  await expect(page).toHaveURL(new RegExp(`locationId=${quarantine.id}`))
  await expect(page).toHaveURL(/bucket=QUARANTINE/)
  await page.getByRole('link', { name: 'Kabel drop', exact: true }).click()
  const position = page.getByRole('region', { name: 'Detail posisi', exact: true })
  await expect(position).toContainText('Tercatat: 100,000 m · Tersedia: 0,000 m')
  await expect(position).toContainText('Pemeriksaan barang')
  expect(explorerMutations).toEqual([])
})
