import { expect, test } from '@playwright/test'
import { pageOf } from '../../src/api/warehouse/codec'
import { location, sku, supplier } from '../../src/api/warehouse/models'
import { login, openWarehouseMenu } from './helpers'
import { captureReference, referenceTenant } from './reference-setup'

test('default Admin manages reference catalog and Manager reads it within granted scope', async ({ page }, info) => {
  test.setTimeout(240_000)
  const fixture = await referenceTenant(page, 'catalog')
  const admin = await fixture.createMember('Admin'), manager = await fixture.createMember('Manager')
  await fixture.activate()
  expect((await page.request.get('/api/areas', { headers: admin.headers })).status()).toBe(403)
  expect((await page.request.get('/api/v1/warehouse/skus', { headers: admin.headers })).status()).toBe(403)
  const reads: string[] = []
  page.on('request', request => { const path = new URL(request.url()).pathname; if (path.startsWith('/api/')) reads.push(path) })
  await login(page, admin.account)
  await page.goto('/warehouse')
  await expect(page.getByRole('heading', { name: 'Barang, Gudang & Pemasok', exact: true })).toBeVisible()
  await openWarehouseMenu(page)
  await expect(page.getByRole('link', { name: 'Barang, Gudang & Pemasok', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Persetujuan Gudang', exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.goto('/warehouse/catalog')
  await page.getByRole('button', { name: 'Tambah barang', exact: true }).click()
  await page.getByRole('textbox', { name: 'Kode barang', exact: true }).fill('CABLE')
  await page.getByRole('textbox', { name: 'Nama barang', exact: true }).fill('Kabel drop')
  await page.getByRole('combobox', { name: 'Pelacakan', exact: true }).selectOption('LOT')
  await page.getByRole('combobox', { name: 'Satuan', exact: true }).selectOption('MM')
  await page.getByRole('textbox', { name: 'Stok minimum (m)', exact: true }).fill('82,500')
  await expect(page.getByRole('checkbox', { name: 'Wajib diperiksa sebelum tersedia', exact: true })).toHaveCount(0)
  await captureReference(page, info, 'admin-cable-form')
  await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
  await captureReference(page, info, 'admin-cable-review')
  const created = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v2/warehouse/skus' && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Simpan barang', exact: true }).click()
  const saved = await created
  expect(saved.status()).toBe(201)
  const cable = sku(await saved.json())
  expect(cable.minimumQuantityBase).toBe('82500')
  expect(cable.inspectionRequired).toBe(false)
  const row = (name: string) => page.getByRole('row').filter({ has: page.getByRole('gridcell', { name, exact: true }) })
  const action = async (name: string, label: string) => {
    await row(name).getByRole('button', { name: 'Aksi baris', exact: true }).click()
    await page.getByRole('menuitem', { name: label, exact: true }).click()
  }
  await action('Kabel drop', 'Ubah')
  await page.getByLabel('Model', { exact: true }).fill('G657A2')
  await page.getByRole('button', { name: 'Tinjau + simpan', exact: true }).click()
  await page.getByRole('button', { name: 'Simpan barang', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const updated = pageOf(sku)(await fixture.get('/api/v2/warehouse/skus', admin.headers)).items.find(value => value.id === cable.id)
  expect(updated?.model).toBe('G657A2')
  expect(updated?.revision).toBe(1)

  await page.getByRole('button', { name: 'Tambah barang', exact: true }).click()
  await page.getByRole('textbox', { name: 'Kode barang', exact: true }).fill('CABLE')
  await page.getByRole('textbox', { name: 'Nama barang', exact: true }).fill('Draf kode ganda')
  await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
  await page.getByRole('button', { name: 'Simpan barang', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await captureReference(page, info, 'duplicate-code-rejected')
  await page.getByRole('button', { name: 'Sebelumnya', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Nama barang', exact: true })).toHaveValue('Draf kode ganda')
  await page.getByRole('button', { name: 'Batal', exact: true }).click()
  await page.getByRole('button', { name: 'Buang perubahan', exact: true }).click()

  await page.getByRole('tab', { name: 'Gudang & Rak', exact: true }).click()
  await expect(page.getByRole('gridcell', { name: fixture.warehouse.name ?? fixture.warehouse.code, exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Tambah lokasi', exact: true }).click()
  await page.getByRole('textbox', { name: 'Kode lokasi', exact: true }).fill('BIN-A')
  await page.getByRole('textbox', { name: 'Nama lokasi', exact: true }).fill('Rak A')
  await page.getByRole('combobox', { name: 'Jenis lokasi', exact: true }).selectOption('BIN')
  await page.getByRole('combobox', { name: 'Lokasi induk', exact: true }).click()
  await page.getByRole('option', { name: (fixture.warehouse.name ?? fixture.warehouse.code) + ' · ' + fixture.warehouse.code, exact: true }).click()
  await expect(page.getByRole('combobox', { name: 'Area lokasi', exact: true })).toHaveValue(fixture.areaId)
  await expect(page.getByText('Izin lihat pengguna diperlukan untuk memilih penanggung jawab.', { exact: true })).toHaveCount(0)
  await captureReference(page, info, 'admin-bin-form')
  await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
  await captureReference(page, info, 'admin-bin-review')
  await page.getByRole('button', { name: 'Simpan lokasi', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const bin = pageOf(location)(await fixture.get('/api/v2/warehouse/locations', admin.headers)).items.find(value => value.code === 'BIN-A')
  expect(bin?.parentLocationId).toBe(fixture.warehouse.id)
  expect(bin?.areaId).toBe(fixture.areaId)
  await page.getByRole('button', { name: 'Tambah lokasi', exact: true }).click()
  await page.getByRole('textbox', { name: 'Kode lokasi', exact: true }).fill('EAST')
  await page.getByRole('textbox', { name: 'Nama lokasi', exact: true }).fill('Gudang Timur')
  await page.getByRole('combobox', { name: 'Area lokasi', exact: true }).selectOption(fixture.areaId)
  await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
  await page.getByRole('button', { name: 'Simpan lokasi', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('gridcell', { name: 'Gudang Timur', exact: true })).toBeVisible()

  await page.getByRole('tab', { name: 'Pemasok', exact: true }).click()
  await page.getByRole('button', { name: 'Tambah pemasok', exact: true }).click()
  await page.getByRole('textbox', { name: 'Kode pemasok', exact: true }).fill('SUPPLIER')
  await page.getByRole('textbox', { name: 'Nama pemasok', exact: true }).fill('Distributor kabel')
  await page.getByLabel('Kontak / referensi', { exact: true }).fill('Tim pengadaan')
  await captureReference(page, info, 'admin-supplier-form')
  await page.getByRole('button', { name: 'Tinjau + buat', exact: true }).click()
  await page.getByRole('button', { name: 'Simpan pemasok', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await action('Distributor kabel', 'Ubah')
  await page.getByLabel('Kontak / referensi', { exact: true }).fill('Kontak baru')
  await page.getByRole('button', { name: 'Tinjau + simpan', exact: true }).click()
  await page.getByRole('button', { name: 'Simpan pemasok', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(pageOf(supplier)(await fixture.get('/api/v2/warehouse/suppliers', admin.headers)).items[0]?.contactReference).toBe('Kontak baru')

  for (const theme of ['light', 'dark']) {
    await page.evaluate(value => localStorage.setItem('ftth.theme', value), theme)
    for (const [tab, name] of [['skus', 'Kabel drop'], ['locations', 'Gudang Timur'], ['suppliers', 'Distributor kabel']]) {
      await page.goto('/warehouse/catalog?tab=' + tab)
      await expect(page.getByRole('gridcell', { name, exact: true })).toBeVisible()
      await captureReference(page, info, theme + '-admin-' + tab)
    }
  }
  expect(reads).not.toContain('/api/areas')
  expect(reads.filter(path => path.startsWith('/api/v1/warehouse/'))).toEqual([])
  await page.goto('/warehouse/receipts')
  await expect(page.getByRole('heading', { name: 'Penerimaan', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, manager.account)
  await page.goto('/warehouse/catalog')
  await expect(page.getByRole('gridcell', { name: 'Kabel drop', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Tambah barang', exact: true })).toHaveCount(0)
  await action('Kabel drop', 'Lihat')
  await expect(page.getByRole('textbox', { name: 'Nama barang', exact: true })).toBeDisabled()
  await expect(page.getByRole('textbox', { name: 'Stok minimum (m)', exact: true })).toHaveValue('82,500')
  await captureReference(page, info, 'manager-read-only-cable')
  await page.getByRole('button', { name: 'Tutup', exact: true }).last().click()
  await page.getByRole('tab', { name: 'Gudang & Rak', exact: true }).click()
  await expect(page.getByRole('gridcell', { name: 'Rak A', exact: true })).toBeVisible()
  await expect(page.getByRole('gridcell', { name: 'Gudang Timur', exact: true })).toHaveCount(0)
  await captureReference(page, info, 'manager-scoped-warehouses')
})
