import { expect, test, type Page } from '@playwright/test'
import { referenceWorkDetail, referenceWorkOrder, workType } from '../../src/api/warehouse/reference'
import { workCustomer } from '../../src/api/warehouse/referenceWorkManagement'
import { login } from './helpers'
import { captureReferenceDocument as capture, referenceTenant } from './reference-setup'

async function choose(page: Page, label: string, name: string) {
  await page.getByRole('combobox', { name: label, exact: true }).click()
  await page.getByRole('option', { name, exact: true }).click()
}
async function saveWork(page: Page, label: string, path: string, method: string) {
  const pending = page.waitForResponse(response => new URL(response.url()).pathname === path && response.request().method() === method)
  await page.getByRole('button', { name: label, exact: true }).click()
  const response = await pending
  expect(response.ok()).toBeTruthy()
  return referenceWorkOrder(await response.json())
}

for (const theme of ['light', 'dark']) {
  test(theme + ' operator creates, edits and reassigns a named task that only its current technician can open', async ({ page }, info) => {
    test.setTimeout(300_000)
    await page.addInitScript(value => localStorage.setItem('ftth.theme', value), theme)
    const fixture = await referenceTenant(page, 'workmanagement')
    const admin = await fixture.createMember('Admin'), technician = await fixture.createMember('Teknisi NE'), replacement = await fixture.createMember('Teknisi FO')
    const customer = workCustomer(await fixture.command('/api/customers', { code: 'CU-1', name: 'Pelanggan Utara', address: 'Jalan Utara', areaId: fixture.areaId, location: { longitude: 106.9, latitude: -6.2 } }))
    await fixture.activate()
    await login(page, admin.account)
    await page.goto('/work-orders')
    await expect(page.getByRole('button', { name: 'Work order baru', exact: true })).toBeVisible()
    await capture(page, info, 'operator-list')
    await page.getByRole('button', { name: 'Work order baru', exact: true }).click()
    await choose(page, 'Jenis pekerjaan', 'Maintenance')
    await choose(page, 'Teknisi penanggung jawab', technician.user.name + ' · ' + technician.user.email)
    await page.getByRole('textbox', { name: 'Judul pekerjaan', exact: true }).fill('Periksa sambungan pelanggan')
    await page.getByRole('textbox', { name: 'Instruksi pekerjaan', exact: true }).fill('Periksa konektor\nCatat redaman terakhir.')
    await choose(page, 'Area pekerjaan', 'Area QA · QA')
    await choose(page, 'Pelanggan pekerjaan', 'Pelanggan Utara · CU-1')
    await page.getByRole('combobox', { name: 'Prioritas pekerjaan', exact: true }).selectOption('HIGH')
    await page.getByLabel('Jadwal pekerjaan', { exact: true }).fill('2026-10-12T16:30')
    await capture(page, info, 'create-task-form')
    await page.getByRole('button', { name: 'Tinjau pekerjaan', exact: true }).click()
    await capture(page, info, 'create-task-review')
    const attempts: { readonly key: string | undefined; readonly body: string | null }[] = []
    await page.route('**/api/v2/work-orders', async route => {
      if (route.request().method() !== 'POST') { await route.continue(); return }
      attempts.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() })
      if (attempts.length === 1) { expect((await route.fetch()).status()).toBe(201); await route.abort('failed') }
      else await route.continue()
    })
    await page.getByRole('button', { name: 'Buat work order', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Sebelumnya', exact: true })).toBeDisabled()
    await capture(page, info, 'uncertain-task-create')
    const created = await saveWork(page, 'Coba transaksi yang sama', '/api/v2/work-orders', 'POST')
    await expect(page.getByRole('button', { name: 'Ubah rincian', exact: true })).toBeVisible()
    await page.unroute('**/api/v2/work-orders')
    expect(attempts).toHaveLength(2); expect(attempts[1]).toEqual(attempts[0])
    expect(created.customerId).toBe(customer.id)
    expect(created.technicianId).toBe(technician.user.id)
    await capture(page, info, 'operator-task-detail')
    await page.getByRole('button', { name: 'Ubah rincian', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Pelanggan pekerjaan', exact: true })).toHaveValue('Pelanggan Utara · CU-1')
    await page.getByRole('textbox', { name: 'Judul pekerjaan', exact: true }).fill('Periksa dan ukur sambungan')
    await capture(page, info, 'edit-task-form')
    await page.getByRole('button', { name: 'Tinjau pekerjaan', exact: true }).click()
    const edited = await saveWork(page, 'Simpan rincian', '/api/v2/work-orders/' + created.id, 'PUT')
    expect(edited.scheduledAt).toBe(created.scheduledAt); expect(edited.customerId).toBe(customer.id)
    await expect(page.getByRole('heading', { name: 'Periksa dan ukur sambungan', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Ganti teknisi', exact: true }).click()
    await choose(page, 'Teknisi pengganti', replacement.user.name + ' · ' + replacement.user.email)
    await capture(page, info, 'reassign-task-form')
    await page.getByRole('button', { name: 'Tinjau pergantian', exact: true }).click()
    await capture(page, info, 'reassign-task-review')
    const reassigned = await saveWork(page, 'Ganti penugasan', '/api/v2/work-orders/' + created.id + '/assignment', 'POST')
    expect(reassigned.assignmentGeneration).toBe(created.assignmentGeneration + 1)
    await expect(page.getByText('Teknisi: ' + replacement.user.name, { exact: true })).toBeVisible()
    await page.goto('/work-orders')
    const overdueRead = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v2/work-orders' && new URL(response.url()).searchParams.get('overdue') === 'true')
    await page.getByRole('tab', { name: 'Sudah ditugaskan', exact: true }).click()
    await page.getByRole('checkbox', { name: 'Hanya tugas terlambat', exact: true }).check()
    expect((await overdueRead).ok()).toBeTruthy()
    await expect(page.getByRole('link', { name: created.code + ' · Periksa dan ukur sambungan', exact: true })).toHaveCount(0)
    await capture(page, info, 'overdue-filter-empty')
    expect((await page.request.get('/api/v2/work-orders/' + created.id, { headers: technician.headers })).status()).toBe(404)
    await page.getByRole('button', { name: 'Keluar', exact: true }).click()
    await login(page, replacement.account)
    await page.goto('/my-work-orders')
    await page.getByRole('link', { name: created.code + ' · Periksa dan ukur sambungan', exact: true }).click()
    await expect(page.getByRole('heading', { name: '1. Instruksi pekerjaan', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Ubah rincian', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Ganti teknisi', exact: true })).toHaveCount(0)
    await capture(page, info, 'current-technician-task')
  })

  test(theme + ' owner manages types while existing task requirements stay immutable', async ({ page }, info) => {
    test.setTimeout(300_000)
    await page.addInitScript(value => localStorage.setItem('ftth.theme', value), theme)
    const fixture = await referenceTenant(page, 'worktypes')
    const admin = await fixture.createMember('Admin'), technician = await fixture.createMember('Teknisi FO')
    await fixture.activate()
    await login(page, fixture.owner)
    await page.goto('/work-orders')
    await page.getByRole('link', { name: 'Kelola jenis pekerjaan', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Jenis Pekerjaan', exact: true })).toBeVisible()
    await capture(page, info, 'owner-types-list')
    await page.getByRole('button', { name: 'Jenis baru', exact: true }).click()
    await page.getByRole('textbox', { name: 'Nama jenis pekerjaan', exact: true }).fill('Pengukuran FO')
    await page.getByRole('combobox', { name: 'Kategori pekerjaan', exact: true }).selectOption('PREVENTIVE')
    await page.getByRole('textbox', { name: 'Nama foto wajib', exact: true }).fill('Lokasi\nHasil pengukuran')
    await capture(page, info, 'new-type-form')
    await page.getByRole('button', { name: 'Tinjau jenis', exact: true }).click()
    await capture(page, info, 'new-type-review')
    const createRead = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v2/work-orders/types' && response.request().method() === 'POST')
    await page.getByRole('button', { name: 'Simpan jenis', exact: true }).click()
    const createdType = await createRead
    expect(createdType.status()).toBe(201)
    const type = workType(await createdType.json())
    await expect(page.getByRole('button', { name: 'Ubah Pengukuran FO', exact: true })).toBeVisible()
    const work = referenceWorkOrder(await fixture.command('/api/v2/work-orders', { typeId: type.id, technicianId: technician.user.id, areaId: fixture.areaId, title: 'Ukur redaman', description: 'Ikuti titik ukur.' }, admin.headers))
    await page.getByRole('button', { name: 'Ubah Pengukuran FO', exact: true }).click()
    await page.getByRole('textbox', { name: 'Nama foto wajib', exact: true }).fill('Foto hasil baru')
    await page.getByRole('checkbox', { name: 'Jenis aktif untuk penugasan baru', exact: true }).uncheck()
    await page.getByRole('checkbox', { name: 'Material wajib dicatat sebelum selesai', exact: true }).check()
    await capture(page, info, 'deactivate-type-form')
    await page.getByRole('button', { name: 'Tinjau jenis', exact: true }).click()
    await page.getByRole('button', { name: 'Simpan jenis', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Ubah Pengukuran FO', exact: true })).toBeVisible()
    const detail = referenceWorkDetail(await fixture.get('/api/v2/work-orders/' + work.id))
    expect(detail.workOrder.type.photoSlots).toEqual(['Lokasi', 'Hasil pengukuran'])
    expect(detail.workOrder.type.materialRequired).toBe(false)
    await page.getByRole('button', { name: 'Hapus Pengukuran FO', exact: true }).click()
    await page.getByRole('button', { name: 'Hapus jenis', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Muat ulang dokumen', exact: true })).toBeVisible()
    await capture(page, info, 'used-type-deletion-rejected')
    await page.getByRole('button', { name: 'Muat ulang dokumen', exact: true }).click()
    const unused = workType(await fixture.command('/api/v2/work-orders/types', { name: 'Jenis sementara', workType: 'REPAIR', materialRequired: false, photoSlots: ['Bukti'] }))
    await page.getByRole('button', { name: 'Muat ulang', exact: true }).click()
    await page.getByRole('button', { name: 'Hapus Jenis sementara', exact: true }).click()
    const deletion = page.waitForResponse(response => new URL(response.url()).pathname === '/api/v2/work-orders/types/' + unused.id && response.request().method() === 'DELETE')
    await page.getByRole('button', { name: 'Hapus jenis', exact: true }).click()
    expect((await deletion).status()).toBe(200)
    await expect(page.getByRole('button', { name: 'Hapus Jenis sementara', exact: true })).toHaveCount(0)
    await capture(page, info, 'saved-types-list')
    await page.getByRole('button', { name: 'Keluar', exact: true }).click()
    await login(page, admin.account)
    await page.goto('/work-orders/types')
    await expect(page.getByRole('button', { name: 'Jenis baru', exact: true })).toHaveCount(0)
    await expect(page.getByText('Akses gudang dibatasi', { exact: true })).toBeVisible()
    await capture(page, info, 'nonowner-type-denied')
  })
}
