import { expect, test, type Page } from '@playwright/test'
import { pageOf, record, uuid } from '../../src/api/warehouse/codec'
import { sku } from '../../src/api/warehouse/models'
import { referencePosition } from '../../src/api/warehouse/reference'
import { referenceRequest, requestDetail } from '../../src/api/warehouse/referenceRequests'
import { technicianPage } from '../../src/api/warehouse/technicians'
import { formatBaseQuantity } from '../../src/api/warehouse/quantity'
import { login } from './helpers'
import { captureReferenceDocument as capture, referenceTenant } from './reference-setup'

async function choose(page: Page, label: string, name: string) {
  await page.getByRole('combobox', { name: label, exact: true }).click()
  await page.getByRole('option', { name, exact: true }).click()
}
async function switchAccount(page: Page, account: { readonly email: string; readonly password: string }) {
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, account)
}
async function requestResponse(page: Page, path: string, label: string) {
  const received = page.waitForResponse(response => new URL(response.url()).pathname === path && response.request().method() === 'POST')
  await page.getByRole('button', { name: label, exact: true }).click()
  const response = await received
  expect(response.ok()).toBeTruthy()
  return referenceRequest(await response.json())
}

for (const theme of ['light', 'dark']) {
  test(theme + ' technician restock becomes own material through reduced Admin review, Manager approval and partial handover retry', async ({ page }, info) => {
    test.setTimeout(300_000)
    await page.addInitScript(value => localStorage.setItem('ftth.theme', value), theme)
    const fixture = await referenceTenant(page, 'requests')
    const admin = await fixture.createMember('Admin'), manager = await fixture.createMember('Manager')
    const technician = await fixture.createMember('Teknisi FO'), other = await fixture.createMember('Teknisi NE')
    const directory = technicianPage(await fixture.get('/api/technicians?size=1', admin.headers))
    expect(directory.totalElements).toBe(2)
    expect(technicianPage(await fixture.get('/api/technicians?size=1&page=1', admin.headers)).items[0]?.id).not.toBe(directory.items[0]?.id)
    const cable = sku(await fixture.command('/api/v2/warehouse/skus', { code: 'DROP', name: 'Kabel drop', tracking: 'LOT', baseUnit: 'MM', inspectionRequired: false }))
    const empty = record(await fixture.command('/api/v2/warehouse/locations', { code: 'EMPTY', name: 'Gudang kosong', kind: 'WAREHOUSE', areaId: fixture.areaId, issueEligible: true }))
    await fixture.command('/api/v1/warehouse/settings/scopes/' + technician.user.id + '/' + uuid(empty.id), { expectedRevision: 0, active: true }, fixture.headers, 'PUT')
    await fixture.activate()
    await fixture.command('/api/v2/warehouse/receipts', { warehouseId: fixture.warehouse.id, lines: [{ skuId: cable.id, quantityBase: '82501' }] }, admin.headers)
    await login(page, technician.account)
    await page.goto('/warehouse/requests')
    await expect(page.getByText('Belum ada permintaan', { exact: true })).toBeVisible()
    await capture(page, info, 'technician-empty-requests')
    await page.getByRole('button', { name: 'Permintaan baru', exact: true }).click()
    await choose(page, 'Material 1', 'Kabel drop · DROP')
    await expect(page.getByRole('region', { name: 'Stok saat ini' }).getByRole('gridcell', { name: '82,501 m', exact: true })).toBeVisible()
    await expect(page.getByRole('region', { name: 'Stok saat ini' }).getByRole('gridcell', { name: 'Gudang kosong', exact: true })).toBeVisible()
    await page.getByRole('textbox', { name: 'Jumlah diminta 1 (m)', exact: true }).fill('82,501')
    await page.getByRole('textbox', { name: 'Alasan permintaan', exact: true }).fill('Kebutuhan pemasangan pelanggan')
    await capture(page, info, 'technician-request-form')
    await page.getByRole('button', { name: 'Tinjau permintaan', exact: true }).click()
    await capture(page, info, 'technician-request-review')
    let view = await requestResponse(page, '/api/v2/warehouse/requests', 'Ajukan permintaan')
    const path = '/api/v2/warehouse/requests/' + view.id
    expect(view.technicianId).toBe(technician.user.id)
    expect((await page.request.get(path, { headers: other.headers })).status()).toBe(404)
    expect((await page.request.get('/api/v2/warehouse/requests/stock-preview?skuId=' + cable.id + '&requestId=' + view.id, { headers: other.headers })).status()).toBe(404)
    expect((await page.request.get('/api/v2/warehouse/stock/' + cable.id, { headers: technician.headers })).status()).toBe(403)
    await expect(page.getByText('Menunggu tinjauan Admin', { exact: true })).toBeVisible()
    await capture(page, info, 'technician-submitted-detail')
    await switchAccount(page, admin.account)
    await page.goto('/warehouse/requests?id=' + view.id)
    await page.getByRole('button', { name: 'Tinjau jumlah', exact: true }).click()
    await page.getByRole('textbox', { name: 'Jumlah disetujui 1 (m)', exact: true }).fill('25')
    await page.getByRole('textbox', { name: 'Catatan tinjauan', exact: true }).fill('Disetujui bertahap sesuai kebutuhan')
    await capture(page, info, 'admin-quantity-review')
    await page.getByRole('button', { name: 'Tinjau persetujuan', exact: true }).click()
    view = await requestResponse(page, path + '/review', 'Simpan tinjauan')
    expect(view.state).toBe('MANAGER_REVIEW')
    expect(view.lines[0].requestedBase).toBe('82501')
    expect(view.lines[0].approvedBase).toBe('25000')
    await switchAccount(page, manager.account)
    await page.goto('/warehouse/requests?id=' + view.id)
    await expect(page.getByRole('button', { name: 'Tinjau jumlah', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Setujui permintaan', exact: true }).click()
    await page.getByRole('button', { name: 'Tinjau keputusan', exact: true }).click()
    await capture(page, info, 'manager-decision')
    view = await requestResponse(page, path + '/decision', 'Setujui permintaan')
    expect(view.state).toBe('APPROVED')
    expect(pageOf(referencePosition)(await fixture.get('/api/v2/warehouse/my-materials', technician.headers)).totalElements).toBe(0)
    await switchAccount(page, admin.account)
    await page.goto('/warehouse/requests?id=' + view.id)
    const attempts: { readonly key: string | undefined; readonly body: string | null }[] = []
    for (const amount of ['12,501', '12,499']) {
      await page.getByRole('button', { name: 'Serahkan Kabel drop', exact: true }).click()
      await choose(page, 'Gudang penyerahan', (fixture.warehouse.name ?? fixture.warehouse.code) + ' · ' + fixture.warehouse.code)
      const positions = pageOf(referencePosition)(await fixture.get('/api/v2/warehouse/stock/' + cable.id + '/positions?availableOnly=true&locationId=' + fixture.warehouse.id, admin.headers))
      const stock = positions.items[0]
      if (!stock) throw new Error('Missing available warehouse stock')
      await choose(page, 'Stok penyerahan 1', [stock.skuName, 'Tanpa serial', formatBaseQuantity(stock.quantityBase, stock.baseUnit) + ' m', stock.stockIdentityId.slice(-8)].join(' · '))
      await page.getByRole('textbox', { name: 'Jumlah diserahkan 1 (m)', exact: true }).fill(amount)
      await capture(page, info, 'handover-form-' + amount)
      await page.getByRole('button', { name: 'Tinjau serah terima', exact: true }).click()
      if (amount === '12,501') {
        await page.route('**' + path + '/handovers', async route => {
          attempts.push({ key: route.request().headers()['idempotency-key'], body: route.request().postData() })
          if (attempts.length === 1) { await route.fetch(); await route.abort('failed') }
          else await route.continue()
        })
        await page.getByRole('button', { name: 'Serahkan ke teknisi', exact: true }).click()
        await expect(page.getByRole('button', { name: 'Sebelumnya', exact: true })).toBeDisabled()
        view = await requestResponse(page, path + '/handovers', 'Coba transaksi yang sama')
        expect(attempts).toHaveLength(2)
        expect(attempts[1]).toEqual(attempts[0])
        await page.unroute('**' + path + '/handovers')
        expect(view.state).toBe('PARTIALLY_FULFILLED')
      } else view = await requestResponse(page, path + '/handovers', 'Serahkan ke teknisi')
      await expect(page.getByRole('textbox', { name: 'Jumlah diserahkan 1 (m)', exact: true })).toHaveCount(0)
      await expect(page.getByRole('region', { name: 'Stok saat ini' }).getByText(amount === '12,501' ? '12,501 m' : '25,000 m', { exact: true })).toBeVisible()
      await capture(page, info, 'handover-detail-' + amount)
    }
    expect(view.state).toBe('FULFILLED')
    const detail = requestDetail(await fixture.get(path, technician.headers))
    expect(detail.timeline.filter(event => event.action === 'HANDOVER')).toHaveLength(2)
    await switchAccount(page, technician.account)
    await page.goto('/my-materials')
    await expect(page.getByRole('gridcell', { name: '12,501 m', exact: true })).toBeVisible()
    await expect(page.getByRole('gridcell', { name: '12,499 m', exact: true })).toBeVisible()
    await capture(page, info, 'technician-own-stock')
    await page.goto('/warehouse/settings')
    await expect(page.getByRole('button', { name: 'Ubah setelan', exact: true })).toHaveCount(0)
    expect((await page.request.get('/api/v2/warehouse/settings', { headers: admin.headers })).status()).toBe(403)
  })

  test(theme + ' proposed procurement retains its policy snapshot and warehouse receipt fulfills directly', async ({ page }, info) => {
    test.setTimeout(300_000)
    await page.addInitScript(value => localStorage.setItem('ftth.theme', value), theme)
    const fixture = await referenceTenant(page, 'procurement')
    const admin = await fixture.createMember('Admin'), manager = await fixture.createMember('Manager'), technician = await fixture.createMember('Teknisi NE')
    const connector = sku(await fixture.command('/api/v2/warehouse/skus', { code: 'CONN', name: 'Konektor', tracking: 'BULK', baseUnit: 'EA', inspectionRequired: false }))
    await fixture.activate()
    await login(page, technician.account)
    await page.goto('/warehouse/requests')
    await page.getByRole('button', { name: 'Permintaan baru', exact: true }).click()
    await page.getByLabel('Jenis permintaan', { exact: true }).selectOption('PROCUREMENT')
    await page.getByLabel('Sumber material 1', { exact: true }).selectOption('NEW')
    await page.getByRole('textbox', { name: 'Nama material baru 1', exact: true }).fill('Konektor tambahan')
    await page.getByRole('textbox', { name: 'Jumlah diminta 1 (unit)', exact: true }).fill('2')
    await page.getByRole('textbox', { name: 'Alasan permintaan', exact: true }).fill('Pengadaan sambungan baru')
    await capture(page, info, 'procurement-proposal')
    await page.getByRole('button', { name: 'Tinjau permintaan', exact: true }).click()
    let view = await requestResponse(page, '/api/v2/warehouse/requests', 'Ajukan permintaan')
    const path = '/api/v2/warehouse/requests/' + view.id
    await switchAccount(page, fixture.owner)
    await page.goto('/warehouse/settings')
    await page.getByRole('button', { name: 'Ubah setelan', exact: true }).click()
    await page.getByRole('checkbox', { name: 'Wajibkan persetujuan Manager', exact: true }).uncheck()
    await page.getByRole('textbox', { name: 'Batas WO terlambat (hari)', exact: true }).fill('5')
    await capture(page, info, 'owner-settings-form')
    await page.getByRole('button', { name: 'Tinjau setelan', exact: true }).click()
    await page.getByRole('button', { name: 'Simpan setelan', exact: true }).click()
    await expect(page.getByText('Tidak wajib', { exact: true })).toBeVisible()
    await capture(page, info, 'owner-settings-saved')
    await switchAccount(page, admin.account)
    await page.goto('/warehouse/requests?id=' + view.id)
    await page.getByRole('button', { name: 'Tinjau jumlah', exact: true }).click()
    await choose(page, 'Barang katalog untuk Konektor tambahan', 'Konektor · CONN')
    await expect(page.getByRole('region', { name: 'Stok saat ini' }).getByRole('gridcell', { name: '0 unit', exact: true })).toBeVisible()
    await capture(page, info, 'admin-proposal-mapping')
    await page.getByRole('button', { name: 'Tinjau persetujuan', exact: true }).click()
    view = await requestResponse(page, path + '/review', 'Simpan tinjauan')
    expect(view.state).toBe('MANAGER_REVIEW')
    expect(view.policyRevision).toBe(0)
    await switchAccount(page, manager.account)
    await page.goto('/warehouse/requests?id=' + view.id)
    await page.getByRole('button', { name: 'Setujui permintaan', exact: true }).click()
    await page.getByRole('button', { name: 'Tinjau keputusan', exact: true }).click()
    view = await requestResponse(page, path + '/decision', 'Setujui permintaan')
    await switchAccount(page, admin.account)
    await page.goto('/warehouse/requests?id=' + view.id)
    for (const amount of ['1', '1']) {
      await page.getByRole('button', { name: 'Terima Konektor', exact: true }).click()
      await choose(page, 'Gudang penerimaan', (fixture.warehouse.name ?? fixture.warehouse.code) + ' · ' + fixture.warehouse.code)
      await page.getByRole('textbox', { name: 'Jumlah aktual (unit)', exact: true }).fill(amount)
      await capture(page, info, 'procurement-receipt-' + view.revision)
      await page.getByRole('button', { name: 'Tinjau barang datang', exact: true }).click()
      view = await requestResponse(page, path + '/receipts', 'Terima barang pengadaan')
      await expect(page.getByRole('textbox', { name: 'Jumlah aktual (unit)', exact: true })).toHaveCount(0)
    }
    expect(view.state).toBe('RECEIVED')
    expect(view.lines[0].receivedBase).toBe('2')
    expect(view.lines[0].fulfilledBase).toBe('0')
    await page.goto('/warehouse/requests')
    await page.getByRole('button', { name: 'Permintaan baru', exact: true }).click()
    await page.getByLabel('Penerima permintaan', { exact: true }).selectOption('WAREHOUSE')
    await choose(page, 'Gudang penerima', (fixture.warehouse.name ?? fixture.warehouse.code) + ' · ' + fixture.warehouse.code)
    await choose(page, 'Material 1', 'Konektor · CONN')
    await page.getByRole('textbox', { name: 'Jumlah diminta 1 (unit)', exact: true }).fill('3')
    await page.getByRole('textbox', { name: 'Alasan permintaan', exact: true }).fill('Pengadaan persediaan gudang')
    await page.getByRole('button', { name: 'Tinjau permintaan', exact: true }).click()
    view = await requestResponse(page, '/api/v2/warehouse/requests', 'Ajukan permintaan')
    const warehousePath = '/api/v2/warehouse/requests/' + view.id
    expect(view.requiresManagerApproval).toBe(false)
    await page.getByRole('button', { name: 'Tinjau jumlah', exact: true }).click()
    await page.getByRole('button', { name: 'Tinjau persetujuan', exact: true }).click()
    view = await requestResponse(page, warehousePath + '/review', 'Simpan tinjauan')
    expect(view.state).toBe('APPROVED')
    await page.getByRole('button', { name: 'Terima Konektor', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Gudang penerimaan', exact: true })).toHaveCount(0)
    await capture(page, info, 'warehouse-fixed-destination')
    await page.getByRole('button', { name: 'Tinjau barang datang', exact: true }).click()
    view = await requestResponse(page, warehousePath + '/receipts', 'Terima barang pengadaan')
    expect(view.state).toBe('FULFILLED')
    expect(view.lines[0].fulfilledBase).toBe('3')
    await expect(page.getByRole('button', { name: 'Serahkan Konektor', exact: true })).toHaveCount(0)
    await capture(page, info, 'warehouse-fulfilled-detail')
    expect(connector.id).toBe(view.lines[0].skuId)
  })
}
