import { expect, test } from '@playwright/test'
import { login, signup } from './helpers'
import { addLocation, addSku, addSupplier, setupOwnArea } from './catalog'
import { confirmOperation, selectNamed } from './fulfillment'
import { setupDiscrepancyApprover } from './approvals'
import { randomUUID } from 'node:crypto'
import { acknowledgeNumericJourney, prepareNumericJourney, switchUser } from './numeric-journey'
import { inspectAsset } from './asset-journey'
import { reassignAndCancelWithCustody } from './reassignment-journey'

// Transfer discrepancy and technician returns use separate tenants and documents.
test('warehouse receives sixty metres and independently resolves forty metres after partial transfer', async ({ page }, testInfo) => {
  test.setTimeout(360_000)
  const admin = await signup(page), area = await setupOwnArea(page, admin)
  const warehouse = await addLocation(page, { code: 'SOURCE', name: 'Gudang asal', area: area.optionLabel })
  const bin = await addLocation(page, { code: 'BIN-A', name: 'Rak asal', area: area.optionLabel, kind: 'BIN', parent: warehouse.label })
  const destination = await addLocation(page, { code: 'DEST', name: 'Gudang tujuan', area: area.optionLabel })
  const transit = await addLocation(page, { code: 'TRANSFER_TRANSIT', name: 'Transit antar gudang', area: area.optionLabel, kind: 'TRANSIT' })
  const inspection = await addLocation(page, { code: 'QA', name: 'Pemeriksaan barang', area: area.optionLabel, kind: 'QUARANTINE' })
  const source = await addLocation(page, { code: 'RECEIPT_SOURCE', name: 'Penerimaan pemasok', area: area.optionLabel, kind: 'TRANSIT' })
  const cable = await addSku(page, { code: 'CABLE', name: 'Kabel transfer', tracking: 'LOT', unit: 'MM', inspectionRequired: false })
  const supplier = await addSupplier(page, 'SUPPLIER', 'Pemasok kabel')
  await page.goto('/warehouse/receipts')
  await page.getByRole('button', { name: 'Buat penerimaan', exact: true }).click()
  await page.getByRole('textbox', { name: 'Referensi surat jalan', exact: true }).fill('SJ-TRANSFER-100')
  await selectNamed(page, 'Pemasok', `${supplier.name} · ${supplier.code}`)
  await selectNamed(page, 'Batas penerimaan', source.label)
  await selectNamed(page, 'Lokasi pemeriksaan', inspection.label)
  await selectNamed(page, 'Barang 1', `${cable.name} · ${cable.code}`)
  await page.getByRole('textbox', { name: 'Panjang reel aktual (m)', exact: true }).fill('100')
  await page.getByRole('textbox', { name: 'Kode lot / reel', exact: true }).fill('REEL-TRANSFER')
  await page.getByText('Konversi kemasan dan biaya', { exact: true }).click()
  await page.getByRole('checkbox', { name: 'Catat biaya kelompok barang', exact: true }).check()
  await page.getByRole('textbox', { name: 'Total biaya (satuan minor)', exact: true }).fill('1000000')
  await page.getByRole('button', { name: 'Tinjau draft', exact: true }).click()
  const receipt = await confirmOperation(page, '/api/v1/warehouse/receipts', 'Simpan draft')
  await page.getByRole('button', { name: 'Terima barang', exact: true }).click()
  await confirmOperation(page, `/api/v1/warehouse/receipts/${receipt.id}/receive`, 'Konfirmasi penerimaan')
  await page.getByRole('button', { name: 'Tempatkan ke bin', exact: true }).click()
  await selectNamed(page, 'Bin tujuan', bin.label)
  await page.getByRole('button', { name: 'Pilih semua yang memenuhi syarat', exact: true }).click()
  await page.getByRole('button', { name: 'Tinjau penempatan', exact: true }).click()
  await confirmOperation(page, `/api/v1/warehouse/receipts/${receipt.id}/putaway`, 'Tempatkan barang')

  const root = '/api/v1/warehouse/transfers'
  await page.goto('/warehouse/transfers')
  await page.getByRole('button', { name: 'Buat transfer', exact: true }).click()
  const positionsRead = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock/positions' && new URL(res.url()).searchParams.get('locationId') === bin.id)
  await selectNamed(page, 'Lokasi asal transfer', bin.label)
  const positions = await (await positionsRead).json()
  expect(positions.items).toHaveLength(1)
  const position = positions.items[0]
  expect(position).toMatchObject({ skuId: cable.id, locationId: bin.id, physical: { quantityBase: '100000' }, available: { quantityBase: '100000' } })
  await selectNamed(page, 'Lokasi tujuan transfer', destination.label)
  await selectNamed(page, 'Lokasi transit transfer', transit.label)
  await selectNamed(page, 'Penerima transfer', admin.name)
  await page.getByRole('textbox', { name: 'Alasan transfer', exact: true }).fill('Pengisian stok gudang tujuan')
  await selectNamed(page, 'Barang transfer 1', `${cable.name} · ${position.stockIdentityId.slice(0, 8)} · 100,000 m`)
  await expect(page.getByText('Lot / reel: REEL-TRANSFER', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Jumlah transfer 1 (m)', exact: true }).fill('100')
  await page.getByRole('button', { name: 'Tinjau transfer', exact: true }).click()
  const draftWrite = page.waitForRequest(req => new URL(req.url()).pathname === root && req.method() === 'POST')
  const draft = await confirmOperation(page, root, 'Simpan transfer')
  expect((await draftWrite).postDataJSON()).toMatchObject({ sourceLocationId: bin.id, destinationLocationId: destination.id, transitLocationId: transit.id,
    lines: [{ sourceBalanceId: position.id, stockIdentityId: position.stockIdentityId, quantityBase: '100000', baseUnit: 'MM' }] })
  expect(draft).toMatchObject({ state: 'DRAFT', revision: 0, lines: [{ quantityBase: '100000', receivedBase: '0', inTransitBase: '0' }] })
  await expect(page.getByRole('region', { name: 'Detail transfer', exact: true })).toContainText(admin.name)
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('transfer-draft.png'), fullPage: true })

  await page.getByRole('button', { name: 'Ubah draft transfer', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Jumlah transfer 1 (m)', exact: true })).toHaveValue('100,000')
  await page.getByRole('textbox', { name: 'Alasan transfer', exact: true }).fill('Rencana pengisian diperiksa sebelum pengiriman')
  await page.getByRole('button', { name: 'Tinjau transfer', exact: true }).click()
  const editWrite = page.waitForRequest(req => new URL(req.url()).pathname === `${root}/${draft.id}` && req.method() === 'PUT')
  const edited = await confirmOperation(page, `${root}/${draft.id}`, 'Simpan transfer', 'PUT')
  expect((await editWrite).postDataJSON()).toMatchObject({ expectedRevision: 0, draft: { lines: [{ sourceBalanceId: position.id, quantityBase: '100000' }] } })
  expect(edited).toMatchObject({ id: draft.id, state: 'DRAFT', revision: 1, lines: [{ receivedBase: '0', inTransitBase: '0' }] })
  await expect(page.getByRole('region', { name: 'Detail transfer', exact: true })).toContainText('Rencana pengisian diperiksa sebelum pengiriman')
  await page.screenshot({ path: testInfo.outputPath('transfer-draft-edited.png'), fullPage: true })

  await page.getByRole('button', { name: 'Kirim ke transit', exact: true }).click()
  const dispatched = await confirmOperation(page, `${root}/${draft.id}/dispatch`, 'Konfirmasi kirim transfer')
  expect(dispatched).toMatchObject({ state: 'DISPATCHED', revision: 2, lines: [{ receivedBase: '0', inTransitBase: '100000' }] })
  await expect(page.getByRole('button', { name: 'Terima transfer', exact: true })).toBeEnabled()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('transfer-dispatched.png'), fullPage: true })
  await page.getByRole('button', { name: 'Terima transfer', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Terima Kabel transfer · REEL-TRANSFER', exact: true }).check()
  await page.getByRole('textbox', { name: 'Jumlah diterima (m)', exact: true }).fill('60')
  await page.getByRole('textbox', { name: 'Referensi bukti transfer', exact: true }).fill('BA-TERIMA-60')
  await page.getByRole('button', { name: 'Tinjau penerimaan', exact: true }).click()
  const received = await confirmOperation(page, `${root}/${draft.id}/receive`, 'Catat penerimaan')
  expect(received).toMatchObject({ state: 'PART_RECEIVED', revision: 3, lines: [{ quantityBase: '100000', receivedBase: '60000', inTransitBase: '40000', resolvedBase: '0' }] })
  expect(received.lines[0].remainingIdentityId).not.toBe(position.stockIdentityId)
  await page.goto('/warehouse/transfers')
  await page.getByRole('link', { name: draft.code, exact: true }).click()
  await expect(page.getByRole('region', { name: 'Detail transfer', exact: true })).toContainText('Sebagian diterima')
  const row = page.getByRole('row').filter({ hasText: 'Identitas asal:' })
  await expect(row.getByRole('gridcell').nth(2).locator('.warehouse-cell-value')).toHaveText('60,000 m')
  await expect(row.getByRole('gridcell').nth(3).locator('.warehouse-cell-value')).toHaveText('40,000 m')
  await page.getByText('Riwayat transfer', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Revisi 3 · Sebagian diterima', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Revisi 0 · Draf', exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('transfer-partial.png'), fullPage: true })

  for (const [bucket, quantity, available, name] of [['TRANSIT', '40000', '0', 'transfer-transit-stock'], ['AVAILABLE', '60000', '60000', 'transfer-received-stock']]) {
    const read = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock' && new URL(res.url()).searchParams.get('bucket') === bucket)
    await page.goto(`/warehouse/stock?bucket=${bucket}`)
    const stock = await (await read).json()
    expect(stock.items).toHaveLength(1)
    expect(stock.items[0]).toMatchObject({ skuId: cable.id, physical: { quantityBase: quantity }, available: { quantityBase: available } })
    await expect(page.getByRole('row').filter({ hasText: 'Kabel transfer' })).toContainText(bucket === 'TRANSIT' ? '40,000 m' : '60,000 m')
    await page.evaluate(() => window.scrollTo(0, 0))
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    await page.screenshot({ path: testInfo.outputPath(`${name}.png`), fullPage: true })
  }

  const lost = await addLocation(page, { code: 'LOST', name: 'Kehilangan terverifikasi', area: area.optionLabel, kind: 'LOST' })
  const checker = await setupDiscrepancyApprover(page, area.checkboxLabel, [bin, destination, transit, lost], [transit, lost])
  await page.screenshot({ path: testInfo.outputPath('discrepancy-policy.png'), fullPage: true })
  await page.goto(`/warehouse/transfers?transferId=${draft.id}`)
  await page.getByRole('button', { name: 'Laporkan selisih', exact: true }).click()
  await selectNamed(page, 'Tujuan penanganan selisih', lost.label)
  await page.getByRole('textbox', { name: 'Alasan selisih', exact: true }).fill('Sisa 40 meter tidak ditemukan setelah penelusuran pengiriman')
  await page.getByRole('textbox', { name: 'Referensi bukti transfer', exact: true }).fill('BA-SELISIH-40')
  await page.getByRole('button', { name: 'Tinjau selisih', exact: true }).click()
  const report = await confirmOperation(page, `${root}/${draft.id}/discrepancy`, 'Catat selisih')
  expect(report).toMatchObject({ state: 'DISCREPANCY', revision: 4, lines: [{ receivedBase: '60000', inTransitBase: '40000', resolvedBase: '0' }] })
  await page.getByRole('link', { name: 'Buka persetujuan gudang', exact: true }).click()
  await expect(page.getByText('Berita acara transfer: BA-SELISIH-40', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Periksa persyaratan persetujuan', exact: true }).click()
  await page.getByRole('button', { name: 'Ajukan persetujuan', exact: true }).click()
  const approval = await confirmOperation(page, '/api/v1/warehouse/approvals/request', 'Kirim permintaan persetujuan')
  expect(approval).toMatchObject({ sourceDocumentId: report.resolutionDocumentId, sourceRevision: 0, revision: 0, status: 'PENDING' })
  await expect(page.getByRole('region', { name: 'Status persetujuan', exact: true })).toContainText('Menunggu persetujuan')
  await expect(page.getByRole('button', { name: 'Setujui permintaan', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('discrepancy-own-denied.png'), fullPage: true })

  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, checker)
  const readReview = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/approvals/${approval.requestId}/details`)
  await page.goto(`/warehouse/approvals?approvalId=${approval.requestId}`)
  const review = await (await readReview).json()
  expect(review).not.toHaveProperty('cost')
  expect(review).toMatchObject({ actions: { canDecide: true }, document: { kind: 'ADJUSTMENT', lines: [{ quantityBase: '40000' }], evidenceReferences: [{ kind: 'TRANSFER', reference: 'BA-SELISIH-40' }] } })
  await expect(page.getByRole('link', { name: 'Buka transfer sumber', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Setujui permintaan', exact: true }).click()
  await page.getByRole('textbox', { name: 'Alasan keputusan / referensi pemeriksaan', exact: true }).fill('Bukti BA-SELISIH-40 dan penerimaan 60 meter sudah diperiksa secara independen')
  await page.getByRole('button', { name: 'Tinjau keputusan', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('discrepancy-independent-review.png'), fullPage: true })
  const decisionRequest = page.waitForRequest(req => new URL(req.url()).pathname === '/api/v1/warehouse/approvals/decide' && req.method() === 'POST')
  const accepted = await confirmOperation(page, '/api/v1/warehouse/approvals/decide', 'Simpan keputusan')
  expect((await decisionRequest).postDataJSON()).toEqual({ requestId: approval.requestId, expectedRevision: 0, decision: 'APPROVE', reason: 'Bukti BA-SELISIH-40 dan penerimaan 60 meter sudah diperiksa secara independen' })
  expect(accepted).toMatchObject({ status: 'APPROVED' })
  await expect(page.getByRole('region', { name: 'Hasil persetujuan dibukukan', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Hasil persetujuan dibukukan', exact: true })).toContainText(accepted.effectOperationId)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('discrepancy-approved.png'), fullPage: true })

  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await login(page, admin)
  const currentRead = page.waitForResponse(res => new URL(res.url()).pathname === `${root}/${draft.id}/details`)
  await page.goto(`/warehouse/transfers?transferId=${draft.id}`)
  expect(await (await currentRead).json()).toMatchObject({ transfer: { revision: 5, state: 'DISCREPANCY', lines: [{ receivedBase: '60000', inTransitBase: '0', resolvedBase: '40000' }] } })
  const resolved = page.getByRole('row').filter({ hasText: 'Identitas asal:' })
  await expect(resolved.getByRole('gridcell').nth(2).locator('.warehouse-cell-value')).toHaveText('60,000 m')
  await expect(resolved.getByRole('gridcell').nth(4).locator('.warehouse-cell-value')).toHaveText('40,000 m')
  await expect(page.getByRole('button', { name: 'Perbaiki laporan selisih', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('discrepancy-resolved-transfer.png'), fullPage: true })
  for (const [status, quantity, available] of [['AVAILABLE', '60000', '60000'], ['LOST', '40000', '0']]) {
    const read = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock/positions' && new URL(res.url()).searchParams.get('status') === status)
    await page.goto(`/warehouse/stock?tab=positions&status=${status}`)
    const stock = await (await read).json()
    expect(stock.items).toHaveLength(1)
    expect(stock.items[0]).toMatchObject({ skuId: cable.id, status, physical: { quantityBase: quantity }, available: { quantityBase: available } })
    await expect(page.getByRole('row').filter({ hasText: 'Kabel transfer' })).toContainText(status === 'AVAILABLE' ? '60,000 m' : '40,000 m')
    await page.screenshot({ path: testInfo.outputPath(`discrepancy-final-${status.toLowerCase()}.png`), fullPage: true })
  }
})

test('original technician returns an unused mixed-case serial after reassignment and cancellation and inspection releases that same unit', async ({ page }, testInfo) => {
  test.setTimeout(360_000)
  const fixture = await prepareNumericJourney(page, { serialPrefix: `Unused-${randomUUID().slice(0, 8)}-` })
  await acknowledgeNumericJourney(page, fixture)
  await reassignAndCancelWithCustody(page, fixture, testInfo)
  await page.goto(`/my-materials?workOrderId=${fixture.workOrder.id}`)
  await page.getByRole('button', { name: 'Kembalikan perangkat', exact: true }).click()
  const scanner = page.getByRole('textbox', { name: 'Serial perangkat', exact: true })
  await scanner.fill(fixture.serial.toLowerCase()); await scanner.press('Enter')
  await page.getByRole('textbox', { name: 'Jumlah dikembalikan (unit)', exact: true }).fill('1')
  await selectNamed(page, 'Karantina tujuan', `${fixture.quarantine.code} · ${fixture.quarantine.name}`)
  await page.getByRole('textbox', { name: 'Referensi bukti pengembalian', exact: true }).fill('Unit belum dipasang; serial utuh dikembalikan')
  await page.getByRole('textbox', { name: 'Alasan pengembalian', exact: true }).fill('Pemasangan perangkat ditunda')
  await page.getByRole('button', { name: 'Tinjau pengembalian', exact: true }).click()
  const returned = await confirmOperation(page, `${fixture.root}/return`, 'Kirim pengembalian')
  expect(returned).toMatchObject({ purpose: 'RETURN', request: { quantityBase: '1', baseUnit: 'EA' } })
  await expect(page.getByRole('button', { name: 'Kembalikan perangkat', exact: true })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('unused-serial-returned-by-technician.png'), fullPage: true })
  await switchUser(page, fixture.admin)
  await page.goto('/warehouse/returns')
  await page.getByRole('button', { name: 'Lihat sisa menunggu penerimaan', exact: true }).click()
  await page.getByRole('button', { name: 'Akui penerimaan sisa', exact: true }).click()
  await page.getByRole('textbox', { name: 'Bukti penerimaan serah-terima', exact: true }).fill('Petugas lain menerima satu unit asli')
  await page.getByRole('button', { name: 'Tinjau serah-terima', exact: true }).click()
  await confirmOperation(page, `${fixture.root}/residuals/acknowledge`, 'Akui penerimaan')
  await page.getByRole('button', { name: 'Terima retur baru', exact: true }).click()
  const source = page.getByRole('combobox', { name: 'Sumber retur', exact: true })
  await expect(source.locator(`option[value="${returned.id}"]`)).toBeAttached()
  await source.selectOption(returned.id)
  await page.getByRole('textbox', { name: 'Referensi bukti penerimaan retur', exact: true }).fill('Serial cocok dengan unit belum terpasang')
  await page.getByRole('button', { name: 'Tinjau penerimaan retur', exact: true }).click()
  const intake = await confirmOperation(page, '/api/v1/warehouse/returns', 'Catat retur')
  expect(intake.stockIdentityId).toBe(returned.transit.stockIdentityId)
  await inspectAsset(page, fixture, intake.id, 'SERVICEABLE', 'ISP')
  const read = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock' && new URL(res.url()).searchParams.get('bucket') === 'AVAILABLE')
  await page.goto('/warehouse/stock?bucket=AVAILABLE')
  const stock = await (await read).json()
  expect(stock.items.find((row: { skuId: string }) => row.skuId === fixture.onu.id)).toMatchObject({ available: { quantityBase: '10' } })
  expect(stock.items.find((row: { skuId: string }) => row.skuId === fixture.cable.id)).toMatchObject({ available: { quantityBase: '900000' } })
  await page.screenshot({ path: testInfo.outputPath('unused-serial-same-unit-available.png'), fullPage: true })
})
