import { expect, test } from '@playwright/test'
import { signup } from './helpers'
import { addLocation, addSku, addSupplier, setupOwnArea } from './catalog'
import { confirmOperation, selectNamed } from './fulfillment'

// Task36: actual warehouse transfer. Technician returns and sold-device RMA are added in task45.
test('warehouse transfers one hundred metres and receives sixty while forty remain in transit', async ({ page }, testInfo) => {
  test.setTimeout(240_000)
  const admin = await signup(page), area = await setupOwnArea(page, admin)
  const warehouse = await addLocation(page, { code: 'SOURCE', name: 'Gudang asal', area: area.optionLabel })
  const bin = await addLocation(page, { code: 'BIN-A', name: 'Rak asal', area: area.optionLabel, kind: 'BIN', parent: warehouse.label })
  const destination = await addLocation(page, { code: 'DEST', name: 'Gudang tujuan', area: area.optionLabel })
  const transit = await addLocation(page, { code: 'TRANSFER_TRANSIT', name: 'Transit antar gudang', area: area.optionLabel, kind: 'TRANSIT' })
  const inspection = await addLocation(page, { code: 'QA', name: 'Pemeriksaan barang', area: area.optionLabel, kind: 'QUARANTINE' })
  const source = await addLocation(page, { code: 'RECEIPT_SOURCE', name: 'Penerimaan pemasok', area: area.optionLabel, kind: 'TRANSIT' })
  const cable = await addSku(page, { code: 'CABLE', name: 'Kabel transfer', tracking: 'LOT', unit: 'MM', inspectionRequired: false })
  const supplier = await addSupplier(page, 'SUPPLIER', 'Pemasok kabel')
  await page.goto('/warehouse/receipts')
  await page.getByRole('button', { name: 'Buat penerimaan', exact: true }).click()
  await page.getByRole('textbox', { name: 'Referensi surat jalan', exact: true }).fill('SJ-TRANSFER-100')
  await selectNamed(page, 'Pemasok', `${supplier.name} · ${supplier.code}`)
  await selectNamed(page, 'Batas penerimaan', source.label)
  await selectNamed(page, 'Lokasi pemeriksaan', inspection.label)
  await selectNamed(page, 'Barang 1', `${cable.name} · ${cable.code}`)
  await page.getByRole('textbox', { name: 'Panjang reel aktual (m)', exact: true }).fill('100')
  await page.getByRole('textbox', { name: 'Kode lot / reel', exact: true }).fill('REEL-TRANSFER')
  await page.getByRole('button', { name: 'Tinjau draft', exact: true }).click()
  const receipt = await confirmOperation(page, '/api/v1/warehouse/receipts', 'Simpan draft')
  await page.getByRole('button', { name: 'Terima barang', exact: true }).click()
  await confirmOperation(page, `/api/v1/warehouse/receipts/${receipt.id}/receive`, 'Konfirmasi penerimaan')
  await page.getByRole('button', { name: 'Tempatkan ke bin', exact: true }).click()
  await selectNamed(page, 'Bin tujuan', bin.label)
  await page.getByRole('button', { name: 'Pilih semua yang memenuhi syarat', exact: true }).click()
  await page.getByRole('button', { name: 'Tinjau penempatan', exact: true }).click()
  await confirmOperation(page, `/api/v1/warehouse/receipts/${receipt.id}/putaway`, 'Tempatkan barang')

  const root = '/api/v1/warehouse/transfers'
  await page.goto('/warehouse/transfers')
  await page.getByRole('button', { name: 'Buat transfer', exact: true }).click()
  const positionsRead = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock/positions' && new URL(res.url()).searchParams.get('locationId') === bin.id)
  await selectNamed(page, 'Lokasi asal transfer', bin.label)
  const positions = await (await positionsRead).json()
  expect(positions.items).toHaveLength(1)
  const position = positions.items[0]
  expect(position).toMatchObject({ skuId: cable.id, locationId: bin.id, physical: { quantityBase: '100000' }, available: { quantityBase: '100000' } })
  await selectNamed(page, 'Lokasi tujuan transfer', destination.label)
  await selectNamed(page, 'Lokasi transit transfer', transit.label)
  await selectNamed(page, 'Penerima transfer', admin.name)
  await page.getByRole('textbox', { name: 'Alasan transfer', exact: true }).fill('Pengisian stok gudang tujuan')
  await selectNamed(page, 'Barang transfer 1', `${cable.name} · ${position.stockIdentityId.slice(0, 8)} · 100,000 m`)
  await expect(page.getByText('Lot / reel: REEL-TRANSFER', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Jumlah transfer 1 (m)', exact: true }).fill('100')
  await page.getByRole('button', { name: 'Tinjau transfer', exact: true }).click()
  const draftWrite = page.waitForRequest(req => new URL(req.url()).pathname === root && req.method() === 'POST')
  const draft = await confirmOperation(page, root, 'Simpan transfer')
  expect((await draftWrite).postDataJSON()).toMatchObject({ sourceLocationId: bin.id, destinationLocationId: destination.id, transitLocationId: transit.id,
    lines: [{ sourceBalanceId: position.id, stockIdentityId: position.stockIdentityId, quantityBase: '100000', baseUnit: 'MM' }] })
  expect(draft).toMatchObject({ state: 'DRAFT', revision: 0, lines: [{ quantityBase: '100000', receivedBase: '0', inTransitBase: '0' }] })
  await expect(page.getByRole('region', { name: 'Detail transfer', exact: true })).toContainText(admin.name)
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('transfer-draft.png'), fullPage: true })

  await page.getByRole('button', { name: 'Kirim ke transit', exact: true }).click()
  const dispatched = await confirmOperation(page, `${root}/${draft.id}/dispatch`, 'Konfirmasi kirim transfer')
  expect(dispatched).toMatchObject({ state: 'DISPATCHED', revision: 1, lines: [{ receivedBase: '0', inTransitBase: '100000' }] })
  await expect(page.getByRole('button', { name: 'Terima transfer', exact: true })).toBeEnabled()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('transfer-dispatched.png'), fullPage: true })
  await page.getByRole('button', { name: 'Terima transfer', exact: true }).click()
  await page.getByRole('checkbox', { name: 'Terima Kabel transfer · REEL-TRANSFER', exact: true }).check()
  await page.getByRole('textbox', { name: 'Jumlah diterima (m)', exact: true }).fill('60')
  await page.getByRole('textbox', { name: 'Referensi bukti transfer', exact: true }).fill('BA-TERIMA-60')
  await page.getByRole('button', { name: 'Tinjau penerimaan', exact: true }).click()
  const received = await confirmOperation(page, `${root}/${draft.id}/receive`, 'Catat penerimaan')
  expect(received).toMatchObject({ state: 'PART_RECEIVED', revision: 2, lines: [{ quantityBase: '100000', receivedBase: '60000', inTransitBase: '40000', resolvedBase: '0' }] })
  expect(received.lines[0].remainingIdentityId).not.toBe(position.stockIdentityId)
  await page.goto('/warehouse/transfers')
  await page.getByRole('link', { name: draft.code, exact: true }).click()
  await expect(page.getByRole('region', { name: 'Detail transfer', exact: true })).toContainText('Sebagian diterima')
  const row = page.getByRole('row').filter({ hasText: 'Identitas asal:' })
  await expect(row.getByRole('gridcell').nth(2).locator('.warehouse-cell-value')).toHaveText('60,000 m')
  await expect(row.getByRole('gridcell').nth(3).locator('.warehouse-cell-value')).toHaveText('40,000 m')
  await page.getByText('Riwayat transfer', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Revisi 2 · Sebagian diterima', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Revisi 0 · Draf', exact: true })).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, 0))
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('transfer-partial.png'), fullPage: true })

  for (const [bucket, quantity, available, name] of [['TRANSIT', '40000', '0', 'transfer-transit-stock'], ['AVAILABLE', '60000', '60000', 'transfer-received-stock']]) {
    const read = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/stock' && new URL(res.url()).searchParams.get('bucket') === bucket)
    await page.goto(`/warehouse/stock?bucket=${bucket}`)
    const stock = await (await read).json()
    expect(stock.items).toHaveLength(1)
    expect(stock.items[0]).toMatchObject({ skuId: cable.id, physical: { quantityBase: quantity }, available: { quantityBase: available } })
    await expect(page.getByRole('row').filter({ hasText: 'Kabel transfer' })).toContainText(bucket === 'TRANSIT' ? '40,000 m' : '60,000 m')
    await page.evaluate(() => window.scrollTo(0, 0))
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    await page.screenshot({ path: testInfo.outputPath(`${name}.png`), fullPage: true })
  }
})
