import { expect, test } from '@playwright/test'
import { createRole, createUser, login, openWarehouseMenu, signup } from './helpers'
import { addLocation, addSku, addSupplier, masterAction, setupOwnArea } from './catalog'

test('real signup, independent approver navigation and explicit unavailable route', async ({ page, request }, testInfo) => {
  const health = await request.get('/actuator/health')
  expect(health.ok()).toBeTruthy()
  expect(health.headers()['content-type']).toContain('json')
  expect(await health.json()).toMatchObject({ status: 'UP', components: { warehouse: { details: {
    database: 'warehouse_e2e', user: 'warehouse_app', marker: process.env.WAREHOUSE_ENVIRONMENT_MARKER,
  } } } })

  await signup(page)
  const roleName = 'Pemeriksa gudang'
  await createRole(page, roleName, ['inventory.approval.view', 'inventory.approval.decide'])
  const approver = await createUser(page, roleName)
  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await login(page, approver)

  const warehouseReads: string[] = []
  page.on('request', req => { if (new URL(req.url()).pathname.startsWith('/api/v1/warehouse/')) warehouseReads.push(new URL(req.url()).pathname) })
  await openWarehouseMenu(page)
  await expect(page.getByRole('link', { name: 'Stok & Perangkat', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Ringkasan Gudang', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Gudang & Logistik', exact: true })).toBeVisible()
  await expect(page.getByText('0 persetujuan menunggu', { exact: true })).toBeVisible()
  const approvalResponse = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/approvals' && new URL(res.url()).search === '?page=0')
  await page.getByRole('link', { name: 'Buka persetujuan gudang', exact: true }).click()
  const response = await approvalResponse
  expect(response.ok()).toBeTruthy()
  expect(await response.json()).toMatchObject({ items: [], page: 0, totalElements: 0 })
  await expect(page.getByText('Tidak ada persetujuan dalam cakupan Anda', { exact: true })).toBeVisible()
  expect(warehouseReads.length).toBeGreaterThan(0)
  expect(warehouseReads.every(path => path === '/api/v1/warehouse/approvals')).toBeTruthy()

  // Obtain this real request's in-memory authorization only for a negative server assertion.
  // No session injection, browser mocks or database seed is used in this journey.
  const authorization = await response.request().headerValue('authorization')
  expect(authorization).toBeTruthy()
  const denied = await request.get('/api/v1/warehouse/stock', { headers: { Authorization: authorization! } })
  expect(denied.status()).toBe(403)
  await page.goto('/warehouse/stock')
  await expect(page.getByText('Akses gudang dibatasi', { exact: true })).toBeVisible()
  await page.goto('/warehouse/missing-page')
  await expect(page.getByText('Halaman gudang tidak tersedia', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Kembali ke ringkasan gudang' }).click()
  await expect(page.getByText('0 persetujuan menunggu', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('approver-navigation.png'), fullPage: true })
})

test('empty tenant creates, edits and archives warehouse masters and grants scoped read-only access through UI', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  const admin = await signup(page)
  await page.goto('/warehouse/catalog')
  await expect(page.getByText('Akun Anda belum memiliki area gudang. Area kosong berarti tidak memiliki akses gudang.', { exact: true })).toBeVisible()
  const area = await setupOwnArea(page, admin)
  const warehouse = await addLocation(page, { code: 'MAIN', name: 'Gudang utama', area: area.optionLabel })
  const bin = await addLocation(page, { code: 'BIN-A', name: 'Rak A', area: area.optionLabel, kind: 'BIN', parent: warehouse.label })
  const quarantine = await addLocation(page, { code: 'QA', name: 'Pemeriksaan barang', area: area.optionLabel, kind: 'QUARANTINE' })
  expect(bin.areaId).toBe(warehouse.areaId)
  await masterAction(page, warehouse.name, warehouse.code, 'Arsipkan')
  const archiveDenied = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/locations/${warehouse.id}/archive`)
  await page.getByRole('button', { name: 'Arsipkan', exact: true }).click()
  expect((await archiveDenied).status()).toBe(409)
  await expect(page.getByRole('alert').filter({ hasText: /referensi|Sumber belum memenuhi/ })).toBeVisible()
  await page.getByRole('button', { name: 'Kembali', exact: true }).click()

  await masterAction(page, bin.name, bin.code, 'Ubah')
  await page.getByRole('textbox', { name: 'Nama lokasi', exact: true }).fill('Rak A-1')
  await page.getByRole('button', { name: 'Tinjau perubahan', exact: true }).click()
  const binUpdate = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/locations/${bin.id}` && res.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Simpan lokasi', exact: true }).click()
  const binSaved = await binUpdate
  expect(binSaved.ok()).toBeTruthy()
  expect(await binSaved.json()).toMatchObject({ revision: 1, name: 'Rak A-1', parentLocationId: warehouse.id, areaId: warehouse.areaId })

  const cable = await addSku(page, { code: 'CABLE', name: 'Kabel drop', tracking: 'LOT', unit: 'MM', minimum: '82,500' })
  expect(cable.minimumQuantityBase).toBe('82500')
  await masterAction(page, cable.name, cable.code, 'Ubah')
  await page.getByRole('textbox', { name: 'Model', exact: true }).fill('G657A2')
  await page.getByRole('button', { name: 'Tinjau perubahan', exact: true }).click()
  const cableUpdate = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/skus/${cable.id}` && res.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Simpan barang', exact: true }).click()
  expect(await (await cableUpdate).json()).toMatchObject({ revision: 1, model: 'G657A2', minimumQuantityBase: '82500' })
  await addSku(page, { code: 'ONU', name: 'ONU pelanggan', tracking: 'SERIAL', minimum: '2' })
  const unused = await addSku(page, { code: 'UNUSED', name: 'Barang percobaan', tracking: 'BULK' })
  await masterAction(page, unused.name, unused.code, 'Arsipkan')
  const archive = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/skus/${unused.id}/archive`)
  await page.getByRole('button', { name: 'Arsipkan', exact: true }).click()
  expect(await (await archive).json()).toMatchObject({ revision: 1, state: 'ARCHIVED' })
  await page.getByRole('combobox', { name: 'Status master', exact: true }).selectOption('ARCHIVED')
  await expect(page.getByRole('gridcell', { name: `${unused.name} ${unused.code}`, exact: true })).toBeVisible()
  await masterAction(page, unused.name, unused.code, 'Lihat')
  await expect(page.getByRole('textbox', { name: 'Nama barang', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Tinjau perubahan', exact: true })).toHaveCount(0)
  await page.goto('/warehouse/catalog?tab=skus')

  await page.getByRole('button', { name: 'Tambah barang', exact: true }).click()
  await page.getByRole('textbox', { name: 'Kode barang', exact: true }).fill('CABLE')
  await page.getByRole('textbox', { name: 'Nama barang', exact: true }).fill('Draf kode ganda')
  await page.getByRole('button', { name: 'Tinjau perubahan', exact: true }).click()
  const duplicate = page.waitForResponse(res => new URL(res.url()).pathname === '/api/v1/warehouse/skus' && res.request().method() === 'POST')
  await page.getByRole('button', { name: 'Simpan barang', exact: true }).click()
  expect((await duplicate).status()).toBe(409)
  await page.getByRole('button', { name: 'Kembali', exact: true }).click()
  await expect(page.getByRole('textbox', { name: 'Nama barang', exact: true })).toHaveValue('Draf kode ganda')
  await page.getByRole('button', { name: 'Batal', exact: true }).click()

  const supplier = await addSupplier(page, 'DISTRIB', 'Distributor material')
  await masterAction(page, supplier.name, supplier.code, 'Ubah')
  await page.getByRole('textbox', { name: 'Kontak / referensi', exact: true }).fill('Bagian pengadaan')
  await page.getByRole('button', { name: 'Tinjau perubahan', exact: true }).click()
  const supplierUpdate = page.waitForResponse(res => new URL(res.url()).pathname === `/api/v1/warehouse/suppliers/${supplier.id}` && res.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Simpan pemasok', exact: true }).click()
  expect(await (await supplierUpdate).json()).toMatchObject({ revision: 1, contactReference: 'Bagian pengadaan' })

  const role = 'Pembaca gudang'
  await createRole(page, role, ['inventory.location.view', 'inventory.item.view', 'inventory.sku.view', 'inventory.receipt.view'])
  const reader = await createUser(page, role, { areas: [area.checkboxLabel], prefix: 'Petugas' })
  await page.goto('/warehouse/catalog?tab=access')
  await page.getByRole('combobox', { name: 'Pengguna', exact: true }).selectOption({ label: `${reader.name} · ${reader.email}` })
  await page.getByRole('combobox', { name: 'Lokasi', exact: true }).selectOption({ label: warehouse.label })
  await page.getByRole('button', { name: 'Berikan akses langsung', exact: true }).click()
  const grant = page.waitForResponse(res => /\/api\/v1\/warehouse\/settings\/scopes\/[^/]+\/[^/]+$/.test(new URL(res.url()).pathname) && res.request().method() === 'PUT')
  await page.getByRole('button', { name: 'Berikan akses', exact: true }).click()
  expect(await (await grant).json()).toMatchObject({ locationId: warehouse.id, active: true, revision: 1 })
  await expect(page.getByText('Pemberian akses langsung: aktif · Revisi 1', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Keluar', exact: true }).click()
  await expect(page).toHaveURL(/\/login$/)
  await login(page, reader)
  await page.goto('/warehouse/catalog?tab=locations')
  await expect(page.getByRole('gridcell', { name: `${warehouse.name} ${warehouse.code}`, exact: true })).toBeVisible()
  await expect(page.getByRole('gridcell', { name: 'Rak A-1 BIN-A', exact: true })).toBeVisible()
  await expect(page.getByRole('gridcell', { name: `${quarantine.name} ${quarantine.code}`, exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Tambah lokasi', exact: true })).toHaveCount(0)
  await expect(page.getByText('Akses baca saja. Minta izin kelola untuk mengubah data.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await page.screenshot({ path: testInfo.outputPath('catalog-readonly.png'), fullPage: true })
})
