import type { WorkOrderView } from '@/api/workorder'
import type { MaterialCustody, MaterialFieldContext, MaterialSettlement } from '@/api/warehouse/materialExecution'
import { materialIds as id, materialPlanFixture, materialSku } from './warehouseMaterialFixture'

export const executionWorkOrder: WorkOrderView = { id: id.source, code: 'WO-MATERIAL', type: 'PREVENTIVE', status: 'IN_PROGRESS', priority: 'NORMAL', title: 'Penarikan kabel', description: null, customerId: null, customerName: null, incidentId: null, areaId: null, destinationLat: null, destinationLng: null, assignees: [{ id: id.inspection, name: 'Budi Teknisi' }], scheduledAt: null, assignedAt: null, startedAt: null, completedAt: null, resolutionNote: null, cancelReason: null, rxBeforeDbm: null, rxAfterDbm: null, approvalStatus: null, approvedBy: null, approvedByName: null, approvedAt: null, approvalNote: null, createdAt: materialPlanFixture.recordedAt }
export function fieldContextFixture(): MaterialFieldContext { return { workOrderId: id.source, workOrderRevision: 5, plan: structuredClone(materialPlanFixture), planState: 'SUBMITTED', useRevision: 0, latestUsageId: null, reworkId: null, evidenceRevision: null } }
export function custodyFixture(): MaterialCustody { return { id: id.piece, receiptId: id.document, issueId: id.issue, issueCode: 'ISS-MATERIAL', issueLineId: id.line, planId: id.plan, planLineId: id.line, sku: materialSku, sourceUsageId: null, quantityBase: '100000', baseUnit: 'MM', stockRevision: 4, location: { id: id.inspection, code: 'FIELD', name: 'Barang Budi' }, serial: null, lotCode: 'REEL-1', initialUseSource: true } }
export function settlementFixture(remaining = '100000'): MaterialSettlement { return { workOrderId: id.source, technicalState: 'IN_PROGRESS', qaState: null, provisioningState: 'NOT_APPLICABLE', materialState: 'OPEN', revision: 7, outstandingBase: remaining, obligations: { workOrderId: id.source, revision: 7, materialState: 'OPEN', dueAt: null, outstandingBase: remaining, reservedUnpickedBase: '0', pickedBase: '0', lines: [{ issueLineId: id.line, stockIdentityId: id.piece, baseUnit: 'MM', issuedBase: '100000', usedBase: (100000n - BigInt(remaining)).toString(), returnedBase: '0', transferredBase: '0', disposedBase: '0', stillAccountableBase: remaining, transitBase: '0', acknowledgedBase: '100000', settledReturnBase: '0' }] } } }
export function usageViewFixture() { return { id: id.evidence, workOrderId: id.source, planId: id.plan, planRevision: 1, useRevision: 1, materialMode: 'MATERIAL_REQUIRED', actor: { id: id.inspection, name: 'Budi Teknisi' }, evidenceReference: 'Pengukuran lapangan 82,5 m', reason: null, recordedAt: materialPlanFixture.recordedAt, lines: [{ id: id.line, receiptId: id.document, issueLineId: id.line, sku: materialSku, quantityBase: '82500', baseUnit: 'MM', residualBase: '17500' }] } }
